### ISSUE TITLE
잘되다가 ...에러발생합니다. 

### ISSUE THREAD

**Issue by inchuli** [naver/yobi#1001]
현재 버전은 0.8.2 입니다
다음과 같이 에러가 발생하여 업데이트 할 버전을 확인하지 못했습니다.

org.eclipse.jgit.api.errors.TransportException: http://repo.yobi.io/naver/yobi: 503 Service Temporarily Unavailable
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:223)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:98)
	at models.YobiUpdate.refreshVersionToUpdate(YobiUpdate.java:82)
	at controllers.SiteApp.update(SiteApp.java:263)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$56$$anonfun$apply$56.apply(routes_routing.scala:1990)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$56$$anonfun$apply$56.apply(routes_routing.scala:1990)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at Global$1.call(Global.java:190)
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57)
	at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:485)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.eclipse.jgit.errors.TransportException: http://repo.yobi.io/naver/yobi: 503 Service Temporarily Unavailable
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:516)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309)
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:202)
	... 45 more

**Comment by npcode** [comment]
http://repo.yobi.io/ 가 죽어있었네요. 살렸습니다.

하지만 가급적 github으로 변경하시는 것이 좋습니다. README 참고: https://github.com/naver/yobi#주의

**Comment by inchuli** [comment]
정상적으로 작동합니다. 
최신버전이  0.8.3인데 ... "현재 버전은 0.8.2 입니다" 라고 나오는건 상관없는건가요?

**Comment by npcode** [comment]
@inchuli 아직 v0.8.3이 릴리즈되지 않아서 최신 버전은 v0.8.2가 맞습니다.
