### ISSUE TITLE
커밋 댓글 입력 오류 관련 

### ISSUE THREAD

**Issue by gt1000** [naver/yobi#1005]
안녕하세요.
커밋 -> 댓글 입력 버튼을 클릭했을 경우 첨부 파일과 같은 오류가 발생 합니다.
원인 및 수정방법을 알고 싶습니다.
좋은 하루 되십시오.

root.log

2015-12-04 12:40:42,037 - [ERROR] - from play in play-akka.actor.default-dispatcher-658
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2015-12-04 12:40:42,037 - [ERROR] - from application in play-akka.actor.default-dispatcher-658

! @6ob6bcg3o - Internal server error, for (GET) [/am-renewal/secureguard-am/commit/fb5206acee1acdbbe59bef6aa814003ae65cfd00] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
        at play.utils.UriEncoding$.encodePathSegment(UriEncoding.scala:46) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.Router$.dynamicString(Router.scala:153) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at controllers.ReverseCodeHistoryApp.newComment(routes_reverseRouting.scala:2068) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at utils.TemplateHelper$DiffRenderer$.urlToPostNewComment(TemplateHelper.scala:444) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.partial_comment_form_on_thread$$anonfun$apply$1.apply(partial_comment_form_on_thread.template.scala:84) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.partial_comment_form_on_thread$$anonfun$apply$1.apply(partial_comment_form_on_thread.template.scala:81) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at play.twirl.api.TemplateMagic$.defining(TemplateMagic.scala:13) ~[com.typesafe.play.twirl-api_2.10-1.0.3.jar:1.0.3]
        at views.html.partial_comment_form_on_thread$.apply(partial_comment_form_on_thread.template.scala:81) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.code.partial_nonrange_codecomment_thread$.apply(partial_nonrange_codecomment_thread.template.scala:107) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.code.diff$$anonfun$apply$4.apply(diff.template.scala:144) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.code.diff$$anonfun$apply$4.apply(diff.template.scala:142) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at views.html.code.diff$.apply(diff.template.scala:142) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.code.diff$.render(diff.template.scala:252) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at views.html.code.diff.render(diff.template.scala) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at controllers.CodeHistoryApp.show(CodeHistoryApp.java:141) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$187$$anonfun$apply$187.apply(routes_routing.scala:3038) ~[yobi.yobi-0.8.2.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$187$$anonfun$apply$187.apply(routes_routing.scala:3038) ~[yobi.yobi-0.8.2.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at Global$1.call(Global.java:190) ~[yobi.yobi-0.8.2.jar:na]
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:80) ~[yobi.yobi-0.8.2.jar:0.8.2]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted

application.log
2015-12-04 12:40:42,037 - [ERROR] - from play in play-akka.actor.default-dispatcher-658
587 Cannot invoke the action, eventually got an error: java.lang.NullPointerException
588
589 2015-12-04 12:40:42,037 - [ERROR] - from application in play-akka.actor.default-dispatcher-658
590
591
592 ! @6ob6bcg3o - Internal server error, for (GET) [/am-renewal/secureguard-am/commit/fb5206acee1acdbbe59bef6aa814003ae65cfd00] ->
593
594 play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
595     at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
596     at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
597     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
598     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
599     at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
600     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
601     at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
602     at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
603     at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
604     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
605     at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
606     at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
607     at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
608     at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
609     at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
610     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
611     at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
612     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
613     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
614     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
615     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
616     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
617 Caused by: java.lang.NullPointerException: null
618     at play.utils.UriEncoding$.encodePathSegment(UriEncoding.scala:46) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
619     at play.core.Router$.dynamicString(Router.scala:153) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
620     at controllers.ReverseCodeHistoryApp.newComment(routes_reverseRouting.scala:2068) ~[yobi.yobi-0.8.2.jar:0.8.2]
621     at utils.TemplateHelper$DiffRenderer$.urlToPostNewComment(TemplateHelper.scala:444) ~[yobi.yobi-0.8.2.jar:0.8.2]
622     at views.html.partial_comment_form_on_thread$$anonfun$apply$1.apply(partial_comment_form_on_thread.template.scala:84) ~[yobi.yobi-0.8.2.jar:0.8.2]
623     at views.html.partial_comment_form_on_thread$$anonfun$apply$1.apply(partial_comment_form_on_thread.template.scala:81) ~[yobi.yobi-0.8.2.jar:0.8.2]
624     at play.twirl.api.TemplateMagic$.defining(TemplateMagic.scala:13) ~[com.typesafe.play.twirl-api_2.10-1.0.3.jar:1.0.3]
625     at views.html.partial_comment_form_on_thread$.apply(partial_comment_form_on_thread.template.scala:81) ~[yobi.yobi-0.8.2.jar:0.8.2]
626     at views.html.code.partial_nonrange_codecomment_thread$.apply(partial_nonrange_codecomment_thread.template.scala:107) ~[yobi.yobi-0.8.2.jar:0.8.2]
627     at views.html.code.diff$$anonfun$apply$4.apply(diff.template.scala:144) ~[yobi.yobi-0.8.2.jar:0.8.2]
628     at views.html.code.diff$$anonfun$apply$4.apply(diff.template.scala:142) ~[yobi.yobi-0.8.2.jar:0.8.2]
629     at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722) ~[org.scala-lang.scala-library-2.10.4.jar:na]
630     at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[org.scala-lang.scala-library-2.10.4.jar:na]
631     at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) ~[org.scala-lang.scala-library-2.10.4.jar:na]
632     at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721) ~[org.scala-lang.scala-library-2.10.4.jar:na]
633     at views.html.code.diff$.apply(diff.template.scala:142) ~[yobi.yobi-0.8.2.jar:0.8.2]
634     at views.html.code.diff$.render(diff.template.scala:252) ~[yobi.yobi-0.8.2.jar:0.8.2]
635     at views.html.code.diff.render(diff.template.scala) ~[yobi.yobi-0.8.2.jar:0.8.2]
636     at controllers.CodeHistoryApp.show(CodeHistoryApp.java:141) ~[yobi.yobi-0.8.2.jar:0.8.2]
637     at Routes$$anonfun$routes$1$$anonfun$applyOrElse$187$$anonfun$apply$187.apply(routes_routing.scala:3038) ~[yobi.yobi-0.8.2.jar:na]
638     at Routes$$anonfun$routes$1$$anonfun$applyOrElse$187$$anonfun$apply$187.apply(routes_routing.scala:3038) ~[yobi.yobi-0.8.2.jar:na]
639     at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
640     at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
641     at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
642     at Global$1.call(Global.java:190) ~[yobi.yobi-0.8.2.jar:na]
643     at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yobi.yobi-0.8.2.jar:0.8.2]
644     at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yobi.yobi-0.8.2.jar:0.8.2]
645     at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:80) ~[yobi.yobi-0.8.2.jar:0.8.2]
 at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
647     at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
648     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
649     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
650     at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
651     at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
652     at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
653     at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
654     at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
655     at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
656     at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
657     at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
658     at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
659     at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
660     at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
661     at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
662     at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
663     at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
664     at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
665     at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
666     at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
667     at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
668     at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
669     at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
670     at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
671     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
672     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
673     ... 6 common frames omitted

**Comment by benelog** [comment]
정상적인 경로로는 재현이 되지 않습니다. 혹시 저장소 디렉토리의 파일들이 다른 곳으로 옮겨졌을 가능성은 없을까요?

저장소 경로는 별다른 설정이 없었다면  /[yobi소스폴더]/target/universal/stage/repo 입니다.  YOBI_HOME 환경변수를 설정하셨다면 그 아래에서 찾으시면 되구요

**Comment by benelog** [comment]
git을 쓰시는지, svn을 쓰시는지도 여부와 해당 commit이 들어간 branch 이름도 알려주셨으면 합니다.

**Comment by benelog** [comment]
에러로그를 봐서는 commit id를 찾는 중에 NPE가 발생하지 않았나 합니다.


## 관련소스 메모

- <https://github.com/naver/yobi/blob/ef8ba0314c44ea2d4b854e9c0667522010f80e66/app/views/partial_comment_form_on_thread.scala.html>
```scala
 <form action="@urlToPostNewComment(thread)" method="post" enctype="multipart/form-data" class="review-form" style="display:block;">
```
- <https://github.com/naver/yobi/blob/ef8ba0314c44ea2d4b854e9c0667522010f80e66/app/utils/TemplateHelper.scala>
```scala
def urlToPostNewComment(thread: CommentThread) = {
      if(thread.isOnPullRequest){
        routes.PullRequestApp.newComment(thread.project.owner, thread.project.name, thread.pullRequest.id, _getCommitId(thread))
      } else {
        routes.CodeHistoryApp.newComment(thread.project.owner, thread.project.name, _getCommitId(thread))
      }
    }

    def _getCommitId(thread: CommentThread) = {
      thread match {
        case (t: CodeCommentThread) =>
          t.commitId
        case (t: models.NonRangedCodeCommentThread) =>
          t.commitId
        case _ => ""
      }
    }

```
- <https://github.com/naver/yobi/blob/ef8ba0314c44ea2d4b854e9c0667522010f80e66/conf/routes>
```
POST /:user/:project/commit/:commitId/comments controllers.CodeHistoryApp.newComment(user, project, commitId)
```
- ./target/scala-2.10/src_managed/main/routes_reverseRouting.scala
```scala
// @LINE:248
def newComment : JavascriptReverseRoute = JavascriptReverseRoute(
   "controllers.CodeHistoryApp.newComment",
   """
      function(user,project,commitId) {
      return _wA({method:"POST", url:"""" + _prefix + { _defaultPrefix } + """" + (""" + implicitly[PathBindable[String]].javascriptUnbind + """)("user", encodeURIComponent(user)) + "/" + (""" + implicitly[PathBindable[String]].javascriptUnbind + """)("project", encodeURIComponent(project)) + "/commit/" + (""" + implicitly[PathBindable[String]].javascriptUnbind + """)("commitId", encodeURIComponent(commitId)) + "/comments"})
      }
   """
)
```

- <https://github.com/naver/yobi/blob/ef8ba0314c44ea2d4b854e9c0667522010f80e66/app/controllers/CodeHistoryApp.java>

**Comment by benelog** [comment]
에러가 나기 전 화면에서 아래와 같은 write-comment-form class가 있는 영역이 어떻게 렌더링되고 있는지 확인해주시면 원인을 찾는데 도움이 될거 같네요

 
```html
 <div class="write-comment-form">
    <form action="/benelog/go-go/commit/d486194b1e5b2d1828c3f05de92d73e828d4ede3/comments" method="post" enctype="multipart/form-data" class="review-form" style="display:block;">
      <input type="hidden" name="thread.id" value="5">
      <div class="author-info-wrap pull-left">
        <div class="author-info">
          <a href="/benelog" class="avatar-wrap medium"
             title="정상혁" data-toggle="tooltip" data-placement="top">
            <img src="/assets/images/default-avatar-128.png" width="32" height="32">
          </a>
        </div>
      </div>
      <div class="write-comment-box">
        <div class="write-comment-wrap">
```

**Comment by gt1000** [comment]
답변 정말 감사 합니다.
별다른 설정은 없었는데~ 이유는 나중에 다시 한번 천천히 확인해 보겠습니다.
우선 다른팀 요청들이 있어서 가벼운 맘으로 다시 한번 설치해 보겠습니다. 
^^ 감사 합니다.

**Comment by gt1000** [comment]
새로 깔고도 동일 현상이 발생 하네요.
별다른 설정 없이 메뉴얼 대로 세팅한게 다인데..... 왜 그럴까요?
