### ISSUE TITLE
클론시 HTTP 505 에러가 발생합니다.

### ISSUE THREAD

**Issue by comseong** [naver/yobi#1029]
git clone http://bbb@yona.aaa.com/bbb/test
Cloning into 'test'...
error: RPC failed; HTTP 505 curl 22 The requested URL returnfed error: 505 HTTP Version Not Supported
atal: The remote end hung up unexpectedly

다음은 서버쪽 에러 로그입니다.
Aug 03 20:36:08 aaa.com restart_yona.sh[493]: [info] a./bbb/test/info/refs?service=git-upload-pack - 83.69.138.223 - bbb [03/Aug/2017:20:36:08 +0500] "GET /bbb/test/info/refs?service=git-upload-pack HTTP/1.0" 200 - - "git/2.12.0.windows.1" 153ms
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [debug] play - Chunked response to HTTP/1.0 request, sending 505 response.
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [info] a./bbb/test/git-upload-pack - 83.69.138.223 - bbb [03/Aug/2017:20:36:09 +0500] "POST /bbb/test/git-upload-pack HTTP/1.0" 200 - - "git/2.12.0.windows.1" 35ms
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: [error] application - uploadPack failed
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: java.io.IOException: Pipe closed
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedInputStream.receive(PipedInputStream.java:226) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_131]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at org.eclipse.jgit.transport.PacketLineOut.writePacket(PacketLineOut.java:141) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
Aug 03 20:36:09 aaa.com restart_yona.sh[493]: at org.eclipse.jgit.transport.PacketLineOut.writePacket(PacketLineOut.java:122) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]

**Comment by comseong** [comment]
Yona issue를 여기에 잘못 올렸네요;
