### ISSUE TITLE
yobi 설치문의드립니다.

### ISSUE THREAD

**Issue by company1234** [naver/yobi#829]
혹시 요비를 설치 완료후, play-2.1.0 폴더자체를 옴기면 다른 곳에서도 바로 실행이되는건지

궁금합니다.

**Comment by company1234** [comment]
음..해봤는데 ../play 실행시킬때 필요한 파일 다운받는 다는 그게 play-2.1.0 안에 설치되는것이 아닌가봅니다.. 옴겼는데 안되네요

그 파일들 어디저장되는지 혹 알수있을까요?....;

**Comment by company1234** [comment]
../play
혹은 (윈도우 사용자일 경우)

..\play
실행하면 필요한 파일들을 web에서 내려받습니다. 첫 실행시 네트워크 상황에 따라 10여분 가까이 소요될 수 있습니다.

이부분에서 네트워크를 통해 ivy.xml 안에있는 파일체크해서 다있으면 바로실행 없으면 다운로드를 하나본데 네트워크가안되는 상황에서는 이 체크하는 부분을 거치지 않게하고싶은데

방법이없을까요?

**Comment by doortts** [comment]
안녕하세요?
네트워크 관련해서는 저희도 고민하고 있습니다.

아마도 다음 메이저 버전 0.8 정도에서 의존 라이브러리가 모두 포함한 dist 버전을 제공하게 될 것 같습니다.
(현재 테스트는 마친상태입니다)

현재는 다른데서 설치한 다음 play 폴더와 yobi 폴더를 통채로 zip이나 tar 등으로 묶어서 이동해야 할 것 같습니다.

**Comment by company1234** [comment]
@doortts 지금 그런방법으로 해보았는데요

**Comment by company1234** [comment]
virtualbox 로 가상 서버 만들어서 실행되도록 업데이트 받아놓고 그 폴더를 통채로 zip으로 옴겼는데

그래도 play 실행시킬때마다 ivy.xml을 찾네요. 

소스 까보니 /framework 에 build 파일을 참조하던데 거기선 또 framework/sbt/sbt.boot.properties 를 참조하구요

이부분에서 

[repositories]
  local
  maven-local
  typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central

이부분이있는데 저 부분에서 외부 인터넷에 있는 ivy.xml을 무조건 체크하게하는건지..

ivy.xml만 찾네요 실행안되고

**Comment by doortts** [comment]
그렇다면 네트워크 되는 쪽에서 play 실행하신 다음
console prompt 가 뜨면 dist 라고 실행해 보시겠어요?

dist 폴더가 생기고 압축파일이 하나 만들어졌을 겁니다.
일종의 배포판인데요 이 압축파일을 네트워크가 안되는 곳으로 옮긴다음
압축을 푸시면 start 파일과 lib 폴더 하나 있을겁니다.

start 파일을 755 권한을 주신다음 실행하시면 됩니다.
이때 application.conf 파일의 설정을 수정해서 사용하고 싶으실수 있는데요
그렇다면 start 로 실행하실때

```
./start -Dconfig.file=./application.conf
```
이런식으로 실행하시면 됩니다.

**Comment by company1234** [comment]
감사합니다 잘 실행 되는것 같아요~!!

근데 한가지 더 질문드리면

이메일 발송부분에서

발송은 잘되었다고하는데 도착하지않는데, 이것도 따로 설정해주어야하는 건가요??

아래는 로그 내역입니다. (to 메일부분은 지웠습니다.)

[debug] i.s.play2.mail - mock email send:
From: yobiproject.mail@gmail.com
To:   
Date: Fri Jan 02 16:07:47 KST 2015
Subj: 요비요비
cont:
요비도비
[debug] i.s.play2.mail - mock email send:
From: yobiproject.mail@gmail.com
To:   
Date: Fri Jan 02 16:07:47 KST 2015
Subj: 요비요비
cont:
요비도비
[info] application - >>>

**Comment by company1234** [comment]
또한가지 질문점이

./start -Dconfig.file=./application.conf

이렇게 실행하면 해당 커멘드에 바로 로그가 올라오는데요

ctrl+c 하면 프로세스까지 꺼져버려서..

혹은, 해당 ssh를 닫으면 프로세스가 꺼지는데

정상실행시키면 ctrl+d 로 exit log 할수있다는데

위처럼 실행시키면 ctrl+d 가 안먹혀서

무슨 방법없을까요?

**Comment by doortts** [comment]
디버그 로그로
``` 
[debug] i.s.play2.mail - mock email send:
```
로 보이는 것으로 보아 application.conf 파일에서
```
#true to use mock mailer for testing, false for using real mail server
smtp.mock = true
```
부분을
```
smtp.mock = false
```
로 만드셔야 할 것 같습니다.

그리고 저도 해보니 ctrl-d가 안되는군요..
슬프네요.. 어쩔수 없이..
```
nohup ./start -Dconfig.file=./application.conf &
````
로 실행해 주셔야 할것 같네요.

만약 nohup 권한이 없는 계정이라면
```
sudo nohup {절대경로}/start -Dconfig.file={절대경로}/application.conf &
````
로 해봐 주세요.

**Comment by company1234** [comment]
혹시 네트워크안되는 환경에서는 메일발송도 안되나요?

Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[javax.mail.mail-1.4.5.jar:1.4.5]        at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]        at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Transport.send0(Transport.java:194) ~[javax.mail.mail-1.4.5.jar:1.4.5]
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_45]        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_45]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_45]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_45]        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_45]        at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_45]

커넥션 타임아웃 뜨는데...흠..ㅠ

**Comment by dearmai** [comment]
@company1234 인터넷과 분리된 망에서 사용하는거면 인터넷 메일로는 전송이 안되는게 맞죠.
특히 로그 보면 smtp.gmail.com 이용하도록 되어있는데 폐쇄망에서 메일 전송 기능은 사용하신다면 자체 smtp 를 구축하고 그걸 사용하도록 변경하셔야 할듯하네요

**Comment by company1234** [comment]
일단 이메일을 제외한 다른 기능은, 수동 설치로 잘 작동합니다.~
