### ISSUE TITLE
#761과 비슷한 에러가 납니다

### ISSUE THREAD

**Issue by seyriz** [naver/yobi#836]
#761 에서 발생했던 에러인데
0.7.3인데도 계속 나네요..

[debug] application - request reset password email by [seyriz:test@dom.co.kr]
org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Domain contains illegal character in string ``logger@dom.co.kr@dom.co.kr''
	at org.apache.commons.mail.Email.createInternetAddress(Email.java:1909)
	at org.apache.commons.mail.Email.setFrom(Email.java:749)
	at org.apache.commons.mail.Email.setFrom(Email.java:732)
	at org.apache.commons.mail.Email.setFrom(Email.java:712)
	at controllers.PasswordResetApp.sendPasswordResetMail(PasswordResetApp.java:80)
	at controllers.PasswordResetApp.requestResetPasswordEmail(PasswordResetApp.java:65)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$59$$anonfun$apply$59.apply(routes_routing.scala:1357)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$59$$anonfun$apply$59.apply(routes_routing.scala:1357)
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:141)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:322)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:31)
	at Global$1.call(Global.java:109)
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:53)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:74)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:73)
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:420)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
Caused by: javax.mail.internet.AddressException: Domain contains illegal character in string ``logger@dom.co.kr@dom.co.kr''
	at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:1269)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:1091)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:633)
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
	at org.apache.commons.mail.Email.createInternetAddress(Email.java:1884)
	... 25 more

**Comment by npcode** [comment]
smtp.user="logger@dom.co.kr" 으로 설정되어있는 상황인가요?

**Comment by seyriz** [comment]
네
네이버 웤스라 도메인이 들어간 이메일이 로그인 아이디입니다.
#761 과 마찬가지로 smtp.domain에 ""을 넣으면 id@dom.co.kr@이 들어가고, 주석처리하면 id@Dom.co.kr@null이 들어갑니다

**Comment by npcode** [comment]
f8ea1ed43dc7ddd15c4e81389f4705a9912b4865 에서 고쳤고, v0.8에 반영될 것입니다.
