### ISSUE TITLE
SVN 한글 파일 업로드시 오류가 발생합니다.

### ISSUE THREAD

**Issue by luckyjun** [naver/yobi#841]
총 4대의 서버에 yobi를 설치하여 테스트 중인데
2대의 서버에만 한글 업로드가 안되고 있습니다.
ubuntu 14.04.1, 12.04
javac 1.7.0_65

잘돌아가는 서버가 있는 반면 잘안돌아가는 서버가 있어 이해가 안갑니다.

도와주세요~~ 

요비 너무 좋은데 오류나서 마음이 아파요~

[info] a./.%.%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8 - 118.129.240.213 - admin [13/Jan/2015:14:12:19 +0900] "MKCOL /svn/admin/test/!svn/wrk/9cf8359b-7657-401a-98ad-1eef796d7749/mes_doc/MES/01.%20%E1%84%92%E1%85%A9%E1%86%B7%E1%84%91%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%8C%E1%85%B5%20%E1%84%86%E1%85%B5%E1%84%83%E1%85%B5%E1%84%8B%E1%85%A5%20%E1%84%80%E1%85%A2%E1%84%89%E1%85%A5%E1%86%AB/02.%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8 HTTP/1.1" 201 - - "SVN/1.7.17 neon/0.29.6" 30ms
30ms
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:472)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:333)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:59)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:472)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:333)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[info] a./svn/admin/test/!svn/act/9cf8359b-7657-401a-98ad-1eef796d7749 - 118.129.240.213 - admin [13/Jan/2015:14:12:19 +0900] "DELETE /svn/admin/test/!svn/act/9cf8359b-7657-401a-98ad-1eef796d7749 HTTP/1.1" 204 - - "SVN/1.7.17 neon/0.29.6" 35ms
[warn] application - OptimisticLockException occurred when updating ProjectVisitation: 1
[info] a./.%.%.pptx - 118.129.240.213 - admin [13/Jan/2015:14:12:19 +0900] "PUT /svn/admin/test/!svn/wrk/9cf8359b-7657-401a-98ad-1eef796d7749/mes_doc/MES/01.%20%E1%84%92%E1%85%A9%E1%86%B7%E1%84%91%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%8C%E1%85%B5%20%E1%84%86%E1%85%B5%E1%84%83%E1%85%B5%E1%84%8B%E1%85%A5%20%E1%84%80%E1%85%A2%E1%84%89%E1%85%A5%E1%86%AB/02.%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8/%E1%84%90%E1%85%A9%E1%86%BC%E1%84%80%E1%85%A8%20%E1%84%89%E1%85%B5%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%86%B7%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8(%E1%84%8B%E1%85%A1%E1%86%AB).pptx HTTP/1.1" 500 - - "SVN/1.7.17 neon/0.29.6" 44ms
[info] a./.%.%.pptx - 118.129.240.213 - admin [13/Jan/2015:14:12:19 +0900] "PUT /svn/admin/test/!svn/wrk/9cf8359b-7657-401a-98ad-1eef796d7749/mes_doc/MES/01.%20%E1%84%92%E1%85%A9%E1%86%B7%E1%84%91%E1%85%A6%E1%84%8B%E1%85%B5%E1%84%8C%E1%85%B5%20%E1%84%86%E1%85%B5%E1%84%83%E1%85%B5%E1%84%8B%E1%85%A5%20%E1%84%80%E1%85%A2%E1%84%89%E1%85%A5%E1%86%AB/02.%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8/%E1%84%90%E1%85%A9%E1%86%BC%E1%84%80%E1%85%A8%20%E1%84%89%E1%85%B5%E1%84%89%E1%85%B3%E1%84%90%E1%85%A6%E1%86%B7%20%E1%84%89%E1%85%A5%E1%86%AF%E1%84%80%E1%85%A8(%E1%84%8B%E1%85%A1%E1%86%AB).pptx HTTP/1.1" 500 - - "SVN/1.7.17 neon/0.29.6" 44ms
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:785)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:508)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:129)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:66)
        at org.jboss.netty.channel.Channels.write(Channels.java:733)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:60)
        at org.jboss.netty.channel.Channels.write(Channels.java:712)
        at org.jboss.netty.channel.Channels.write(Channels.java:679)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2.handle(PlayDefaultUpstreamHandler.scala:257)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:129)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:128)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend$1$$anonfun$apply$1.apply(Promise.scala:104)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:785)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:508)[debug] play - java.nio.channels.ClosedChannelException

        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:129)[debug] play - java.nio.channels.ClosedChannelException

        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:66)
        at org.jboss.netty.channel.Channels.write(Channels.java:733)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:60)
        at org.jboss.netty.channel.Channels.write(Channels.java:712)
        at org.jboss.netty.channel.Channels.write(Channels.java:679)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2.handle(PlayDefaultUpstreamHandler.scala:257)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:129)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:128)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
        at play.api.libs.concurrent.PlayPromise$$anonfun$extend$1$$anonfun$apply$1.apply(Promise.scala:104)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[info] a./svn/admin/test/mes_doc - 118.129.240.213 - - [13/Jan/2015:14:12:48 +0900] "OPTIONS /svn/admin/test/mes_doc HTTP/1.1" 200 - - "SVN/1.7.17 neon/0.29.6" 18ms

**Comment by doortts** [comment]
안녕하세요?
한글만 안된다는 의미가...

svn 으로 commit 할때 한글 파일이 포함되면 서버로 commit 이 정상적으로 이루어지지 않는다는 의미이신건가요?

ps.
`요비 너무 좋은데...` 부분 에서 흔들렸습니다. : )

**Comment by luckyjun** [comment]
네 꼭 한글이 이라서가 아니더라구요." /폴더/폴더/파일이름 " 이렇게 해서 너무 길면 안올라가고 서버마 잠시 멈쳐 있는데. (ssh, ping 이 안됨) 그리고 가끔 저런 오류나 나오고 있어요.

**Comment by doortts** [comment]
@luckyjun 서버의 기본 캐릭터 인코딩이 어떻게 되어 있는지, 혹시 다른서버와는 다르게 세팅되어 있는건 아닌지 확인 부탁드립니다.
