### ISSUE TITLE
코드를 볼 수가 없네요 ......

### ISSUE THREAD

**Issue by blueguy** [naver/yobi#849]
코드 보기에서..  
하위 디렉토리로 계속 내려가다가, 소스 코드를 확인할 수가 없는 경우가 발생했습니다. 

뭐가 문제일까요?

2015-01-22 14:47:53,315 - [ERROR] - from application in play-internal-execution-context-2 

! @6l0n49l8n - Internal server error, for (GET) [/UDACITY/ggumddakji/code/master/!/Ggumddakji/app/src/main/java/com/asg/ggumddakji] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:289) ~[play_2.10.jar:2.1.0]
	at play.api.DefaultApplication.handleError(Application.scala:383) [play_2.10.jar:2.1.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:132) [play_2.10.jar:2.1.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$2$$anonfun$handle$1.apply(PlayDefaultUpstreamHandler.scala:128) [play_2.10.jar:2.1.0]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play_2.10.jar:2.1.0]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113) [play_2.10.jar:2.1.0]
	at play.api.libs.concurrent.PlayPromise$$anonfun$extend$1$$anonfun$apply$1.apply(Promise.scala:104) [play_2.10.jar:2.1.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
java.lang.NullPointerException: null
	at playRepository.GitRepository$ObjectFinder.fixRevCommitNoParents(GitRepository.java:477) ~[classes/:na]
	at playRepository.GitRepository$ObjectFinder.access$100(GitRepository.java:326) ~[classes/:na]
	at playRepository.GitRepository$ObjectFinder$1.next(GitRepository.java:412) ~[classes/:na]
	at playRepository.GitRepository$ObjectFinder$1.next(GitRepository.java:404) ~[classes/:na]
	at playRepository.GitRepository$ObjectFinder.find(GitRepository.java:372) ~[classes/:na]
	at playRepository.GitRepository.treeAsJson(GitRepository.java:320) ~[classes/:na]
	at playRepository.GitRepository.getMetaDataFromPath(GitRepository.java:238) ~[classes/:na]
	at controllers.CodeApp.ajaxRequestWithBranch(CodeApp.java:128) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$176$$anonfun$apply$176.apply(routes_routing.scala:2294) ~[classes/:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$176$$anonfun$apply$176.apply(routes_routing.scala:2294) ~[classes/:na]
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:141) ~[play_2.10.jar:2.1.0]
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:322) ~[play_2.10.jar:2.1.0]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:31) ~[play_2.10.jar:2.1.0]
	at Global$1.call(Global.java:109) ~[classes/:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:53) ~[classes/:na]
	at actions.DefaultProjectCheckAction.call(DefaultProjectCheckAction.java:38) ~[classes/:na]
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:72) ~[classes/:na]
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:74) ~[play_2.10.jar:2.1.0]
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:73) ~[play_2.10.jar:2.1.0]
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:420) ~[play_2.10.jar:2.1.0]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) ~[akka-actor_2.10.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) ~[akka-actor_2.10.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) ~[akka-actor_2.10.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) ~[akka-actor_2.10.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) ~[akka-actor_2.10.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502) ~[akka-actor_2.10.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) ~[scala-library.jar:na]

**Comment by npcode** [comment]
next 브랜치의 95df526 에서 해결한 이슈인 것 같은데요. v0.8에 반영될 것입니다.
