### ISSUE TITLE
업데이트 체크 오류 및 태그등록시 색상지정 오류

### ISSUE THREAD

**Issue by yongbeam** [naver/yobi#864]
일단 첫번째로 관리계정으로 업데이트확인을 하면 아래와 같이 오류가 발생합니다.

-----
업데이트
현재 버전은 0.7.3 입니다
다음과 같이 에러가 발생하여 업데이트 할 버전을 확인하지 못했습니다.
org.eclipse.jgit.api.errors.TransportException: http://repo.yobi.io/naver/yobi: 503 Service Temporarily Unavailable
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:223)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:101)
	at models.YobiUpdate.refreshVersionToUpdate(YobiUpdate.java:85)
	at controllers.SiteApp.update(SiteApp.java:263)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$56$$anonfun$apply$56.apply(routes_routing.scala:1333)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$56$$anonfun$apply$56.apply(routes_routing.scala:1333)
	at play.core.Router$HandlerInvoker$$anon$6$$anon$2.invocation(Router.scala:141)
	at play.core.Router$Routes$$anon$1.invocation(Router.scala:322)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:31)
	at Global$1.call(Global.java:109)
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:53)
	at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:37)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:74)
	at play.core.j.JavaAction$$anon$2.apply(JavaAction.scala:73)
	at play.libs.F$Promise$PromiseActor.onReceive(F.java:420)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425)
	at akka.actor.ActorCell.invoke(ActorCell.scala:386)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230)
	at akka.dispatch.Mailbox.run(Mailbox.scala:212)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:502)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
Caused by: org.eclipse.jgit.errors.TransportException: http://repo.yobi.io/naver/yobi: 503 Service Temporarily Unavailable
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:516)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309)
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:202)
	... 25 more
-----
일시적인 현상인가요? 잘되다가 이렇게 나오네요 503이면 서버오류인데 확인부탁드립니다

두번째로 프로젝트별 태그라벨을 등록하는데 색상이 바뀌지 않습니다.
즉, 컬러값이 고정되어서 신규 라벨을 등록시에는 처음에 선택되어진 색상만 선택이 가능합니다.
예를들어 처음에 신규로 생성할때 컬러코드가 #40a0eb 로 되어있다면 다른색을 선택하여도 #40a0eb로 고정되어 색상변경이 되질않습니다.
( 직접 코드값을 입력해서 적용하면잘됩니다. 기본으로 이미 지정되어 있는 12가지의 색상이 문제입니다 )
마지막으로 이미 등록된 라벨을 수정할때는 정상동작합니다

0.7.3 사용중이고 우분투를 사용하고 있습니다.

**Comment by npcode** [comment]
repo.yobi.io가 죽었네요... 살려야겠습니다.

**Comment by doortts** [comment]
;;;;;;;;;;;;

**Comment by npcode** [comment]
살렸습니다.
