### ISSUE TITLE
윈도우에서 테스트 해보니 몇가지 문제점 알려드립니다.

### ISSUE THREAD

**Issue by pokev25** [naver/yobi#907]
1.  설치 설명서에서 자동링크가 잘못 걸렸습니다. 
      Yobi 최신 버전(http://yobi.io/yobi.zip)을 다운받아서 압축을 풉니다. 

     스페이스 한 칸 필요 해 보입니다.

2. yobi.bat를 실행시키고 접속하니 관리자 정보입력 화면이 나옵니다.
    서버를 재시작해야 합니다.....라고 나오는데 재시작 방법을 모르겠습니다.

   bat파일 종료하면 되나? 싶어서 ctrl+c 누르고 재시작 하면 

  Play server process ID is 5116
Oops, cannot start the server.
javax.persistence.PersistenceException: The default EbeanServer has not been defined? This is normally set via the ebean.datasource.default property. Otherwise it should be registered programatically via registerServer()
        at com.avaje.ebean.Ebean$ServerManager.getPrimaryServer(Ebean.java:178)
        at com.avaje.ebean.Ebean$ServerManager.access$300(Ebean.java:128)
        at com.avaje.ebean.Ebean.find(Ebean.java:1071)
        at Global.insertInitialData(Global.java:159)
        at Global.onStart(Global.java:138)
        at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

어디인가 프로세스가 남아 있는게 문제인듯 한데 뭔지 모르겠어서
PC를 재부팅하고 yobi.bat를 실행시키면 다시 관리자 정보 입력 화면이 나옵니다.

**Comment by npcode** [comment]
2번 문제는 Yobi가 설정파일을 찾지 못하는 상황인 것 같네요. 재시작하라는 안내 메시지에 혹시 application.secret을 설정하라는 메시지도 포함되어있나요?

**Comment by pokev25** [comment]
환영합니다!

서버를 재시작해야합니다. 

라고만 적혀 있습니다.

**Comment by npcode** [comment]
그럼 application.conf에 application.secret은 잘 설정했는데, 그 application.conf를 찾지 못하고 있는 것 같군요.

conf/application.conf 파일과 conf/application-logger.xml을 직접 지정해줘야 할 것 같은데, 한번 이런식으로 실행해보시겠어요?

`bin/yobi.bat -Dconfig.file=conf/application.conf -Dlogger.file=conf/application-logger.xml`

**Comment by pokev25** [comment]
안됩니다. 윈도우라서
bin/yobi.bat은 실행되지 않아 bin\yobi.bat으로 실행시켰고

파라메터지정은 / 로 하나 \ 로 하나 둘다

**Comment by npcode** [comment]
원인을 알 것 같네요. 이거 Play 버그라서 bin/yobi에서는 이 문제를 우회하는 스크립트를 추가했는데 bin/yobi.bat에는 추가를 안했군요.

**Comment by npcode** [comment]
build.sbt를 고쳐서 bat 파일을 위한 스크립트도 추가해야겠군요.

**Comment by npcode** [comment]
@naver/yobi-committers 윈도에서 자바 옵션 주는 법 아시는 분?

**Comment by npcode** [comment]
@pokev25 -Dconfig.file=conf\application.conf 로 / 대신 \를 넣어도 같은 에러가 나오나요?

**Comment by minje** [comment]
저도 지금 2번과같은 상황인데.. 아직 윈도우용 yobi.bat 에는 해당 내용이 추가가

안된건가요?

**Comment by npcode** [comment]
@minje 네, 아직 안되었습니다. 일단은 bin/yobi.bat 실행할 때 자바 옵션으로 config.file과 logger.file을 설정하면 동작할 것입니다.

**Comment by ajpat** [comment]
안녕하세요. 저도 윈도우즈에서 동일한 문제를 가지고 있는데, 
bin\yobi.bat 실행할때 자바옵션으로 설정하면 된다고 하셨는데, 
좀 더 구체적으로 알려주실 수 있나요? (명령어 예제식으로 ... )
어떻게 하면 되는 건지 몰라서 문의합니다.

**Comment by ShiningD** [comment]
저도 동일한 증상으로 조치를 못하고 있는 상황인데요.
혹시, 언제쯤 윈도우 버전 버그가 수정될 지 알 수 있을까요?
git으로 소스코드를 받아 실행해도 activoator 쪽에 문제가 발생해서(최신버전의 activator min버전을 받아도 발생하여..)
현재는 압축버전을 다운로드 받는것을 기다리고 있습니다.

**Comment by npcode** [comment]
@ShiningD Yobi 0.8.1의 README 대로 하셨는데도 안되는 것인지요?

**Comment by ShiningD** [comment]
@npcode 제가 activator 버전을 상위버전으로 실행해서 오류가 난 것 같습니다. readme에 명시되어 있는 버전으로 실행하니 이상없이 되네요. 다만, run에서는 이상없이 작동하는데, start 명령어로 실행하면 아래와 같은 에러메시지와 함께 종료 됩니다.

$ ..\activator
[info] Loading project definition from C:\yobi-master\yobi\project
[info] Set current project to yobi (in build file:/C:/yobi-master/yobi/)
[yobi] $ start
[info] Wrote C:\yobi-master\yobi\target\scala-2.10\yobi_2.10-0.8.1.pom
[info] Compiling 2 Java sources to C:\yobi-master\yobi\target\scala-2.10\classes...
[info] Compiling 1 Scala source and 11 Java sources to C:\yobi-master\yobi\target\scala-2.10\classes...
[info] Compiling 188 Scala sources and 222 Java sources to C:\yobi-master\yobi\target\scala-2.10\classes...
[info] Packaging C:\yobi-master\yobi\target\scala-2.10\yobi_2.10-0.8.1.jar ...
[info] Done packaging.

(Starting server. Type Ctrl+D to exit logs, the server will remain in background)

오류: 기본 클래스 play.core.server.NettyServer을(를) 찾거나 로드할 수 없습니다.
