### ISSUE TITLE
ArrayIndexOutOfBoundsException 발생

### ISSUE THREAD

**Issue by zepinos** [naver/yobi#912]
다음과 같은 오류가 발생합니다. (TortoiseSVN)

Error XML parsing failed:(200 OK)

로그에는 다음과 같은 오류가 보입니다.

2015-06-01 17:12:57,951 - [ERROR] - from application in Thread-4963 
java.lang.ArrayIndexOutOfBoundsException
        at org.tmatesoft.svn.core.io.diff.SVNDiffWindow.apply(SVNDiffWindow.java:360)
        at org.tmatesoft.svn.core.internal.delta.SVNDeltaCombiner.addWindow(SVNDeltaCombiner.java:225)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.getContents(FSInputStream.java:171)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.readContents(FSInputStream.java:114)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.read(FSInputStream.java:98)
        at org.tmatesoft.svn.core.internal.wc.SVNFileUtil.readIntoBuffer(SVNFileUtil.java:309)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.readToBuffer(SVNDeltaGenerator.java:279)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.sendDelta(SVNDeltaGenerator.java:154)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepositoryUtil.sendTextDelta(FSRepositoryUtil.java:259)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffFiles(FSUpdateContext.java:461)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:538)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.drive(FSUpdateContext.java:312)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepository.finishReport(FSRepository.java:559)
        at org.tmatesoft.svn.core.internal.io.fs.FSTranslateReporter.finishReport(FSTranslateReporter.java:47)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVUpdateHandler.execute(DAVUpdateHandler.java:433)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVReportHandler.execute(DAVReportHandler.java:177)
        at org.tmatesoft.svn.core.internal.server.dav.DAVServlet.service(DAVServlet.java:132)
        at controllers.SvnApp$1.run(SvnApp.java:151)

**Comment by npcode** [comment]
체크아웃 할 때 인가요? 젠킨스에서도 비슷한 문제가 있다는 얘기가 있네요.

https://issues.jenkins-ci.org/browse/JENKINS-9646

**Comment by doortts** [comment]
안녕하세요? TortoiseSVN으로 어떤 작업을 할때 발생하셨나요?

**Comment by zepinos** [comment]
업데이트 받다가요. 다시 시도하면 저 오류 뜬 이후로 작업이 진행은 됩니다.
