### ISSUE TITLE
ArrayIndexOutOfBoundsException 오류

### ISSUE THREAD

**Issue by zepinos** [naver/yobi#915]
다음과 같은 오류가 발생합니다.

[error] application - java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.tmatesoft.svn.core.io.diff.SVNDiffWindow.apply(SVNDiffWindow.java:360)
        at org.tmatesoft.svn.core.internal.delta.SVNDeltaCombiner.addWindow(SVNDeltaCombiner.java:225)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.getContents(FSInputStream.java:171)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.readContents(FSInputStream.java:114)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.read(FSInputStream.java:98)
        at org.tmatesoft.svn.core.internal.wc.SVNFileUtil.readIntoBuffer(SVNFileUtil.java:309)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.readToBuffer(SVNDeltaGenerator.java:279)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.sendDelta(SVNDeltaGenerator.java:154)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepositoryUtil.sendTextDelta(FSRepositoryUtil.java:259)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffFiles(FSUpdateContext.java:461)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:538)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.drive(FSUpdateContext.java:312)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepository.finishReport(FSRepository.java:559)
        at org.tmatesoft.svn.core.internal.io.fs.FSTranslateReporter.finishReport(FSTranslateReporter.java:47)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVUpdateHandler.execute(DAVUpdateHandler.java:433)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVReportHandler.execute(DAVReportHandler.java:177)
        at org.tmatesoft.svn.core.internal.server.dav.DAVServlet.service(DAVServlet.java:132)
        at controllers.SvnApp$1.run(SvnApp.java:151)

모든 데이터를 update 받은 사용자가 TortoiseSVN 으로 commit 할 때 발생합니다. 파일 한 개만 올려도 발생하고, 용량은 그리 크지 않은 것입니다.

**Comment by npcode** [comment]
재현이 잘 안되는데요. 몇몇 저장소에서만 발생하는 이슈인가요?

**Comment by zepinos** [comment]
사내에 저장소가 1개 밖에 없어서...

이번 문제는 svn 리버전 중 특정 리버전에서 checksum mismatch 가 있는 디렉토리가 보여서(백업 도중 알았습니다) 해당 디렉토리 삭제 후 다시 올렸는데, 삭제 전 폴더를 받은 사람들에게서 문제가 발생했던 것 같습니다. 해당 디렉토리를 revert 하고 진행하니 정상적으로 넘어간 것 같네요.
