### ISSUE TITLE
0.8 업그레이드 오류

### ISSUE THREAD

**Issue by WooJin-Jeon** [naver/yobi#917]
0.8로 업그레이드 중 오류가 발생합니다.
윈도우즈서버입니다.

진행 사항은 아래와 같습니다.

### 1. `bin\yobi.bat` 실행 시 아래와 같은 오류가 발생합니다.
```
Oops, cannot start the server.
javax.persistence.PersistenceException: The default EbeanServer has not been defined? This is
via registerServer()
        at com.avaje.ebean.Ebean$ServerManager.getPrimaryServer(Ebean.java:178)
        at com.avaje.ebean.Ebean$ServerManager.access$300(Ebean.java:128)
        at com.avaje.ebean.Ebean.find(Ebean.java:1071)
        at Global.insertInitialData(Global.java:159)
        at Global.onStart(Global.java:138)
        at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

### 2. #907 참조 하여 아래처럼 실행
`SET JAVA_OPTS=-Dconfig.file=conf/application.conf -Dlogger.file=conf/application-logger.xml`
`bin\yobi.bat`

실행 시 아래와 같은 오류 발생
```
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:Unique index or primary key violation: "PRIMAR
Y KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.ISSUE_COMMENT_VOTER ADD CONSTRAINT PUBLIC.FK_ISSUE_COMMENT_VOTER_ISSUE FOREIGN KEY(ISSUE_COMMENT_ID) REFERENCES PUBLIC.ISSUE_COMMENT(ID) NOCHECK [23505-176]
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.ISSUE_COMMENT_VOTER ADD CONSTRAINT PUBLIC.FK_ISSUE_COMMENT_VOTER_ISSUE FOREIGN KEY(ISSUE_COMMENT_ID) REFERENCES PUBLIC.ISSUE_COMMENT(ID) NOCHECK [23505-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.index.PageDataIndex.getNewDuplicateKeyException(PageDataIndex.java:166)
        at org.h2.index.PageDataIndex.add(PageDataIndex.java:144)
        at org.h2.store.PageStore.addMeta(PageStore.java:1808)
        at org.h2.index.PageBtreeIndex.<init>(PageBtreeIndex.java:64)
        at org.h2.table.RegularTable.addIndex(RegularTable.java:235)
        at org.h2.command.ddl.AlterTableAddConstraint.createIndex(AlterTableAddConstraint.java:280)
        at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:205)
        at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
        at org.h2.engine.MetaRecord.execute(MetaRecord.java:59)
        at org.h2.engine.Database.open(Database.java:719)
        at org.h2.engine.Database.openDatabase(Database.java:260)
        at org.h2.engine.Database.<init>(Database.java:254)
        at org.h2.engine.Engine.openSession(Engine.java:57)
        at org.h2.engine.Engine.openSession(Engine.java:164)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
        at org.h2.engine.Engine.createSession(Engine.java:125)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
        ... 22 more
```

### 3. #913 참조하여 DB 복구 시도
`java -cp $PLAY_HOME/repository/local/com.h2database/h2/1.3.168/jars/h2.jar org.h2.tools.Recover`
`java -cp $PLAY_HOME/repository/local/com.h2database/h2/1.3.168/jars/h2.jar org.h2.tools.RunScript -url jdbc:h2:file:yobi -user "" -script yobi.h2.sql`

실행 시 아래와 같은 오류 발생
```
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Table "O_2" already exists; SQL statement:

-- pageSize: 2048 writeVersion: 3 readVersion: 3
-- head 1: writeCounter: 936165 log 664:15403/15405 crc -447908223 (ok)
-- head 2: writeCounter: 936165 log 664:15403/15405 crc -447908223 (ok)
-- log 664:15403/15405
-- page 3: free list
-- 3 1111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111
-- 100 1111111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111 - 1111111111 1111111111
...
...
...
-- page 4: data node parent: 0 table: -1 entries: 3 rowCount: 185
-- page 5: data leaf (last) parent: 11 table: 2 entries: 83 columns: 3
CREATE TABLE O_2(C0 VARCHAR, C1 VARCHAR, C2 VARCHAR) [42101-168]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
        at org.h2.message.DbException.get(DbException.java:169)
        at org.h2.message.DbException.get(DbException.java:146)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:108)
        at org.h2.command.CommandContainer.update(CommandContainer.java:75)
        at org.h2.command.Command.executeUpdate(Command.java:230)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
        at org.h2.tools.RunScript.process(RunScript.java:253)
        at org.h2.tools.RunScript.process(RunScript.java:186)
        at org.h2.tools.RunScript.process(RunScript.java:317)
        at org.h2.tools.RunScript.runTool(RunScript.java:140)
        at org.h2.tools.RunScript.main(RunScript.java:68)
```

해결책이 있을까요..?

**Comment by npcode** [comment]
restore/runscript 대신 script/runscript 하는 방법을 써 보심이 좋겠습니다. DB 업그레이드시 문제가 생길때는그렇게 하는 쪽이 정석인 것 같네요. 하는 방법은 http://www.h2database.com/html/tutorial.html#upgrade_backup_restore 에 나와있습니다.
