### ISSUE TITLE
SVN 업데이트 실패

### ISSUE THREAD

**Issue by zepinos** [naver/yobi#919]
아래와 같은 오류가 발생합니다.

[error] application - java.lang.ArrayIndexOutOfBoundsException
        at org.tmatesoft.svn.core.io.diff.SVNDiffWindow.apply(SVNDiffWindow.java:360)
        at org.tmatesoft.svn.core.internal.delta.SVNDeltaCombiner.addWindow(SVNDeltaCombiner.java:225)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.getContents(FSInputStream.java:171)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.readContents(FSInputStream.java:114)
        at org.tmatesoft.svn.core.internal.io.fs.FSInputStream.read(FSInputStream.java:98)
        at org.tmatesoft.svn.core.internal.wc.SVNFileUtil.readIntoBuffer(SVNFileUtil.java:309)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.readToBuffer(SVNDeltaGenerator.java:279)
        at org.tmatesoft.svn.core.io.diff.SVNDeltaGenerator.sendDelta(SVNDeltaGenerator.java:154)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepositoryUtil.sendTextDelta(FSRepositoryUtil.java:259)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffFiles(FSUpdateContext.java:461)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:538)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:413)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:413)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:413)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:413)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:413)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.diffDirs(FSUpdateContext.java:357)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.updateEntry(FSUpdateContext.java:533)
        at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.drive(FSUpdateContext.java:312)
        at org.tmatesoft.svn.core.internal.io.fs.FSRepository.finishReport(FSRepository.java:559)
        at org.tmatesoft.svn.core.internal.io.fs.FSTranslateReporter.finishReport(FSTranslateReporter.java:47)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVUpdateHandler.execute(DAVUpdateHandler.java:433)
        at org.tmatesoft.svn.core.internal.server.dav.handlers.DAVReportHandler.execute(DAVReportHandler.java:177)
        at org.tmatesoft.svn.core.internal.server.dav.DAVServlet.service(DAVServlet.java:132)
        at controllers.SvnApp$1.run(SvnApp.java:151)

계속적으로 update 시 반응이 없길래 로그를 보니 다음과 같은 오류가 발생하였습니다.

svn 프로토콜로 직접 update 을 받은 후 다시 update 등의 작업을 진행하니 정상적으로 진행이 되었습니다.

0.8.0 으로 업그레이드 되면서 너무 불안정해진 것 같습니다.

**Comment by npcode** [comment]
SVNKit이 생각보다 좀 불안한 것 같네요. Yobi 1.0에서는 외부 SVN 저장소와 연동할 수 있도록 하는 안을 검토중입니다.
