### ISSUE TITLE
0.7.3에서 0.8 업그레이드 문의

### ISSUE THREAD

**Issue by alzkdpf** [naver/yobi#921]
#913 과 동일한 문제로 참고해 업그레이드 진행했으나 잘 안되내요. ^^;;
우선 #913 처럼 기본 백업 파일을 yobi 폴더로 복원후 아래처럼 실행했습니다.
start -DapplyEvolutions.default=true -Dhttp.port=9001
이경우 사이트가 새로 생성되서 댓글 참조해서 아래처럼 home과 conf 지정했는데 
이때는 관리자 계정 패스워드가 맞지 않는다는 오류가 나내요.
start -Dhttp.port=9001 -Dyobi.home=/path/yobi -Dconfig.file=/path/yobi/conf/application.conf

문서에도 찾기 힘들어서 ^^;; 
0.7.3 에서 백업파일외에 옮겨야될 설정파일이나 폴더가 어떤게 있는지? 그리고 어디로 옮겨야할지?
내공이 부족해 여쭤봅니다. 그리고 실행 명령어도 어떻게 하면 깔끔하게 옮길 수 있을까요?

**Comment by yongseokleecom** [comment]
조금 다르지만 제가 격은 이슈 입니다. #913 
제가 업그레이드 한 순서입니다. 
1. http://yobi.io/yobi.zip 바이너리 다운로드
2. yobi.h2.db restore/runscript 명령어를 이용하여 yobi.h2.db 새로 생성
4. yobi.zip 압축해제
5. repo / uploads / yobi.h2.db 해제한 경로로 이동
6. 기존 0.7.3 conf/application.conf 에서 커스텀한 내용을 0.8 conf/application.conf 반영
7. 기동
도움 되셨으면 좋겠습니다 ~

**Comment by npcode** [comment]
@alzkdpf 현재 문서 파일이 잘못되어 확인 및 수정중입니다. 

아마 현재 DB 파일이 잘못해서 2개가 만들어진 상황일 수 있을 것 같은데요. 최초 시작시 사이트 관리자 계정을 생성했던 DB가 아닌 다른 DB를 사용하고 계실 가능성이 있습니다. /path/yobi/conf/application.conf 파일의 db.default.url에서 다음과 같이 db 위치를 절대경로로 지정해보시면 잘 될 것입니다.

DB 파일이 /path/to/db.h2.db 라면:

    db.default.url="jdbc:h2:file:/path/to/db;MODE=PostgreSQL"

**Comment by alzkdpf** [comment]
두분 답변 감사합니다.
우선 conf 파일 경로와 db.default.url이 지정이 안되었을 경우 무조건 새로 생성되는 듯 합니다. 
해서 conf 수정후 start 명령에 conf에대한 부분 명시해서 실행하는데 ^^;; 조금 길긴하지만 

db는 읽어 오는것 같은데 #913 과 같은 오류가 발생하는거 같은데 내용은 아래처럼 나옵니다.
복구 옵션으로 제공해주신 recover 와 스크립트 둘다 사용해서 db 복구한뒤 실행해도 마찬가지내요.

해결 방법이 따로 있을까요??

[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.ISSUE_COMMENT_VOTER ADD CONSTRAINT PUBLIC.FK_ISSUE_COMMENT_VOTER_ISSUE FOREIGN KEY(ISSUE_COMMENT_ID) REFERENCES PUBLIC.ISSUE_COMMENT(ID) NOCHECK [23505-176]
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.ISSUE_COMMENT_VOTER ADD CONSTRAINT PUBLIC.FK_ISSUE_COMMENT_VOTER_ISSUE FOREIGN KEY(ISSUE_COMMENT_ID) REFERENCES PUBLIC.ISSUE_COMMENT(ID) NOCHECK [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.PageDataIndex.getNewDuplicateKeyException(PageDataIndex.java:166)
	at org.h2.index.PageDataIndex.add(PageDataIndex.java:144)
	at org.h2.store.PageStore.addMeta(PageStore.java:1808)
	at org.h2.index.PageBtreeIndex.<init>(PageBtreeIndex.java:64)
	at org.h2.table.RegularTable.addIndex(RegularTable.java:235)
	at org.h2.command.ddl.AlterTableAddConstraint.createIndex(AlterTableAddConstraint.java:280)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:205)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.engine.MetaRecord.execute(MetaRecord.java:59)
	at org.h2.engine.Database.open(Database.java:719)
	at org.h2.engine.Database.openDatabase(Database.java:260)
	at org.h2.engine.Database.<init>(Database.java:254)
	at org.h2.engine.Engine.openSession(Engine.java:57)
	at org.h2.engine.Engine.openSession(Engine.java:164)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
	at org.h2.engine.Engine.createSession(Engine.java:125)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:74)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:215)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	... 22 more

**Comment by npcode** [comment]
runscript 실행할 때 h2 1.3.176으로 하셨는지요?

정확하게 하려면 script는 h2 1.3.175로, runscript는 1.3.176으로 해야 할 것 같네요. (사실 전 저 현상을 재현하지 못해서 그렇게 해야하는지 확인은 못했습니다)

**Comment by yongseokleecom** [comment]
@npcode 
restore시 yobi 0.7.3에 있는 h2 라이브러리를 사용하고
runscript에는 yobi 0.8에 있는 h2 라이브러리를 사용했습니다.

**Comment by alzkdpf** [comment]
1.3.176 대신 기존 0.7.3에 포함되서 제공되던 1.3.168 버전으로 진행했습니다. ^^;;
그럼 제가 실수 했내용. 자세한 내용 감사합니다. 다시 해보겠습니다
