### ISSUE TITLE
0.8 업그레이드시 DB관련 오류 발생

### ISSUE THREAD

**Issue by namineya** [naver/yobi#923]
오류 내용은 아래와 같습니다.
기존에 사용중인 yobi.h2.db 를 덮어쓰기 한 후 실행을 하니 발생한 오류입니다.
이 오류 관련하여 참고할만한 이슈가 있다면 피드백 부탁 드립니다.

Picked up _JAVA_OPTIONS: -Xmx2048m -Xms1024m
Play server process ID is 3575
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: null.Message:Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.NOTIFICATION_EVENT_N4USER ADD CONSTRAINT PUBLIC.FK_NOTIFICATION_EVENT_N4USER__01 FOREIGN KEY(NOTIFICATION_EVENT_ID) REFERENCES PUBLIC.NOTIFICATION_EVENT(ID) NOCHECK [23505-176]
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON """".PAGE_INDEX"; SQL statement:
ALTER TABLE PUBLIC.NOTIFICATION_EVENT_N4USER ADD CONSTRAINT PUBLIC.FK_NOTIFICATION_EVENT_N4USER__01 FOREIGN KEY(NOTIFICATION_EVENT_ID) REFERENCES PUBLIC.NOTIFICATION_EVENT(ID) NOCHECK [23505-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
        at org.h2.message.DbException.get(DbException.java:154)
        at org.h2.index.PageDataIndex.getNewDuplicateKeyException(PageDataIndex.java:166)
        at org.h2.index.PageDataIndex.add(PageDataIndex.java:144)
        at org.h2.store.PageStore.addMeta(PageStore.java:1808)
        at org.h2.index.PageBtreeIndex.<init>(PageBtreeIndex.java:64)
        at org.h2.table.RegularTable.addIndex(RegularTable.java:235)
        at org.h2.command.ddl.AlterTableAddConstraint.createIndex(AlterTableAddConstraint.java:280)
        at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:205)
        at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
        at org.h2.engine.MetaRecord.execute(MetaRecord.java:59)
        at org.h2.engine.Database.open(Database.java:719)
        at org.h2.engine.Database.openDatabase(Database.java:260)
        at org.h2.engine.Database.<init>(Database.java:254)
        at org.h2.engine.Engine.openSession(Engine.java:57)
        at org.h2.engine.Engine.openSession(Engine.java:164)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
        at org.h2.engine.Engine.createSession(Engine.java:125)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:331)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at java.sql.DriverManager.getConnection(DriverManager.java:571)
        at java.sql.DriverManager.getConnection(DriverManager.java:215)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
        ... 22 move

**Comment by npcode** [comment]
h2database 버그로 저런 문제가 발생하는 경우가 있는 것으로 알려져있습니다.

https://github.com/naver/yobi/issues/913#issuecomment-108202668 를 참고하셔서 DB 마이그레이션을 시도해보시는 것이 좋을 것 같습니다.

**Comment by namineya** [comment]
#924 를 참고하여 정상 페이지까지 확인 하였습니다. 그런데 로그인 시 암호가 맞지 않다고 나오는데 혹시 어떤 문제일런지요? 복원은 zip파일로 백업을 한 후 진행하였습니다.

**Comment by npcode** [comment]
@namineya 혹시 application.secret 값이 바뀌었는지요?

**Comment by namineya** [comment]
@npcode 접속을 하고 admin 계정생성을 하는 항목에서 더이상 진행하지 않았으며 일반 계정으로 접속을 시도하여도 동일하게 패스워드 문제로 접속하지 못하고 있습니다. 재발급 받기 위해 시도도 해봤지만 메일 주소도 변경이 된건지 아니면 복원에 문제가 있는건지 진행이 되지 않고 있습니다. ㅠㅠ

업그레이드로 진행을 하고자 했지만 처리 하는 과정에서 문제가 있는거 같아 0.8을 위해 새롭게 폴더를 만들어 진행을 한 상태입니다. db라던지 백업해야 할 항목들은 백업 후 복원한 상태입니다.

**Comment by npcode** [comment]
@namineya 재발급을 시도하면 어떻게 되는지요?

**Comment by npcode** [comment]
@namineya 다른 데이터들은 보이는데 로그인만 안되는 상황인지요?

**Comment by namineya** [comment]
@npcode 비밀번호 재발급을 하기 위해 관련 정보를 입력하고 나면 아래와 같이 나옵니다.
메일 발송에 실패했습니다.
잘못된 비밀번호 재 설정 요청입니다.

그리고 로그인 하지 않은 상태에서 프로젝트 목록에 들어가면 저희가 설정한 내용때문에 프로젝트 리스트는 나오지 않고 있습니다.

**Comment by namineya** [comment]
@npcode 메일 발송 관련하여서는 0.7.3버전에서 정상적으로 사용 중이었습니다. (gmail계정을 사용중)
혹시 0.8로 넘어오면서 메일설정 부분이 변경 된게 있는지요?

**Comment by npcode** [comment]
"잘못된 비밀번호 재 설정 요청입니다"라는 에러는 메일 주소 혹은 로그인 아이디가 불일치할 때 발생하는 에러인데요. 아예 메일 발송 이전에 에러가 발생한 것으로 보입니다.

DB 상태에 뭔가 문제가 있어보이는데요. 다음과 같은 방법으로 데이터베이스에 콘솔로 접근하여 select * from n4user; 하셔서 사용자 테이블이 정상적인지 확인해 보시겠어요?

    java -cp ~/.ivy2/cache/com.h2database/h2/jars/h2-1.3.176.jar org.h2.tools.Shell -user "" -password "" -url "jdbc:h2:file:./yobi"

ps. 0.8에서 메일 발송 기능에 꽤 수정된 부분이 있긴 합니다. 다만 설정에는 변한 것이 없습니다.

**Comment by namineya** [comment]
@npcode 알려주신대로 접속하여 확인 결과 

ID  | NAME    | LOGIN_ID      | PASSWORD                                     | PASSWORD_SALT                                                              | EMAIL                         | AVATAR_URL | REMEMBER_ME | CREATED_DATE            | STATE   | LAST_STATE_MODIFIED_DATE | LANG
1   | 관리자     | admin         | 9SXdxxxxxxxxxx49NHZQYKiz5+DYgeeYA1iDfgY= | [44, -107, 125, -62, 14, 19, -41, 41, 110, 61, 18, 42, 122, 109, 122, -78] | xxxxx@xxxx.co.kr            | null       | FALSE       | 2012-11-01 17:00:00.0   | null    | null                     | ko

위와 같이 admin 정보를 확인 할 수 있었습니다.(xxxxx는 임의로 변경한 내용입니다.)
그외에 일반 계정또한 별다른 문제가 있어 보이지는 않습니다.

**Comment by npcode** [comment]
DB에 문제가 없어보이는군요. n4user 테이블을 못 읽어서 생기는 문제라고 생각했는데 좀 이상하네요. 설치하신 Yobi에서 admin의 프로필 페이지(예: http://localhost:9000/admin )에는 접근하면 정상적으로 admin 사용자의 프로필이 보이는지요?

**Comment by namineya** [comment]
@npcode 마이페이지라고 보이구요 다른건 존재하지 않는걸로 해서 페이지가 나오긴 합니다.

**Comment by npcode** [comment]
admin 사용자에 대한 비밀번호 리셋에 실패했다면 이런 로그가 남아있을텐데요:

```
[debug] application - request reset password email by [admin:xxxxx@xxxx.co.kr]
[debug] application - wrong user: admin
```

로그에 남아있는 메일주소가 DB에 기록된 것과 같은가요? 같은데도 저런 로그가 남으면 정말 뭔가 이상한거라서요.

**Comment by namineya** [comment]
@npcode 진짜 이상한가봐요 ㅠㅠ
[debug] application - request reset password email by [admin: xxxx@xxxx.co.kr]
[debug] application - wrong user: admin

DB에 기록된것과 동일한 메일주소입니다.ㅠㅠ

**Comment by npcode** [comment]
흠 좀 많이 이상하네요. 혹시 Git 클라이언트로 코드 저장소 접근할때는 유저 인증이 되나요?

**Comment by npcode** [comment]
로그인이나 비밀번호 리셋 쪽에 버그가 있나 해서요.

**Comment by namineya** [comment]
@npcode 유저인증 안됩니다. 그리고 상태는 오프라인 상태로 확인이 됩니다.

**Comment by namineya** [comment]
@npcode 다운그레이드 하는 방법이 있을지요? 0.7.3으로 다시 돌아가야 할꺼 같아서요(개발팀에서 사용하고 있는지라 복구가 안되면 큰일나는지라...)

**Comment by npcode** [comment]
넵. 다운그레이드는 그냥 업그레이드하는 것과 같은 요령으로 하시면 됩니다. 다만 업그레이드 할 때 -DapplyEvolutions.default=true 를 하셨다면 반대로 -DapplyDownEvolutions.default=true 를 주셔야 정상적으로 DB가 다운그레이드됩니다. (안 주면 에러남)

하지만 user 테이블에 접근이 안되는 문제라면 다운그레이드로 해결이 될런지 잘 모르겠네요

근데 user 테이블에 저

**Comment by npcode** [comment]
혹시 사용자를 새로 만들어서 로그인하는 건 잘 되나요?

**Comment by npcode** [comment]
admin 프로필 페이지에 들어갔을 때 정상적으로 사이트 관리자 이름과 프로젝트 갯수(아마 사이트의 모든 프로젝트 갯수일 것입니다)가 표시되는지요?

![2015-06-08 15 54 03](https://cloud.githubusercontent.com/assets/1129852/8029431/01702464-0df8-11e5-9cb9-c1a5580de8c3.png)

**Comment by doortts** [comment]
증상 자체만으로는 application.secret 값이 변경되었을때 발생하는것과 유사한데요.

**Comment by npcode** [comment]
@doortts application.secret이 바뀌어도 로그인엔 영향 안줄 것 같네요. salt는 사용자별로 DB 테이블에 저장되어있어서...

**Comment by namineya** [comment]
@npcode test 아이디 생성해서 로그인한 결과 이상없습니다.
로그인 하지 않은 상태에서 admin 프로필 페이지로 들어가면 내용이 보여야 정상인가요? 그렇다면 데이타 존재 하지 않는걸로 나온다고 이야기 드려야 할거 같아요

**Comment by npcode** [comment]
@namineya 네 보여야 정상이고, 만약 아니라면 user 테이블에 접근이 안되는것이겠네요.

추측으로는 아예 다른 DB에 접근하고 있는 것이 아닌가 싶습니다. 데이터가 하나라도 있는지 확인할 수 없으니 뭐라 말씀드리기가 힘드네요.

conf/application.conf에 들어가셔서 db.default.url 설정을 고쳐서 DB 파일 경로를 절대 경로로 지정해보시는 것이 어떤지요?

**Comment by npcode** [comment]
admin 프로필 페이지 들어갔는데 이름 란에 "존재하지 않는 사용자"라는 식으로 나와있으면 데이터가 없는 것입니다.

**Comment by namineya** [comment]
@npcode 알려주신 URL로 어드민 페이지에 접속하면 다음과 같이 표시가 됩니다.

확인 URL - http://monosnap.com/image/N6D1FNmXl94k1EKSsFAyKaatC8z7hl

파일경로 문제인가요? 절대경로 수정은 이미 되어 있습니다. 수정한 내용은 
db.default.url="jdbc:h2:file:/data/activator-1.2.10-minimal/yobi;MODE=PostgreSQL"

잘못 된 부분이 있는지요?

**Comment by doortts** [comment]
db 파일 지정이 잘못되었나 본데요. `/data/activator-1.2.10-minimal/` 디렉터리내에 .db 파일이 어떤게 있나요? 목록 보여주실수 있으세요?

**Comment by namineya** [comment]
@doortts /data/activator-1.2.10-minimal/yobi/ 여기에 .db가 있습니다. 그럼 경로가 jdbc:h2:file:/data/activator-1.2.10-minimal/yobi/yobi 이렇게 되어야 하는건가요?

**Comment by npcode** [comment]
@namineya 넵 그게 맞습니다.

**Comment by namineya** [comment]
@npcode @doortts ㅠㅠ db파일 경로가 잘못되어 발생한 문제였습니다. 
@npcode 제가 소중한 시간을 뺏은거 같습니다. 정말 죄송합니다. 저의 무지로 인해 ㅠㅠ
@npcode @doortts 마지막 까지 저의 질문에 답변 주셔서 감사합니다

**Comment by npcode** [comment]
천만에요. 0.8 버그로 설치가 복잡해져서 생긴 문제입니다. 피드백 주셔서 감사합니다.
