### ISSUE TITLE
application.conf 파일을 변경했는데도 적용이 안되고 있습니다.

### ISSUE THREAD

**Issue by KudoLayton** [naver/yobi#925]
conf/application.conf.default 파일을 복사하여 conf/application.conf에서 
signup.require.confirm을 true로 해서 비공개 회원제도로 운영하려고 했는데 서버를 재시작 해도 conf가 적용되지 않고 있습니다.

**Comment by npcode** [comment]
-Dconfig.file 설정으로 application.conf 파일의 위치를 지정하면 정상 동작하는지요?

예: bin/yobi -Dconfig.file=/path/to/application.conf

**Comment by KudoLayton** [comment]
git을 설치했는데 Dconfig.file의 위치를 잘 모르겠습니다.

**Comment by alzkdpf** [comment]
yobi 실행시 기존에
- start -DapplyEvolutions.default=true -Dhttp.port=9000

대신 
- start -DapplyEvolutions.default=true -Dhttp.port=9000 -Dconfig.file=~설치경로/activator-1.2.10-minimal/yobi/conf/application.conf

위 명령어로 실행하셔도되고 새로운 가이드에 set 하는 방법이 나와있내요. 찾아보시면 도움되실 것 같습니다.

**Comment by KudoLayton** [comment]
아하 activator안에서 하는 거군요.
감사합니다 ^^

**Comment by KudoLayton** [comment]
이전 방법대로 옵션을 설정하니 이번엔 nettyException이라는 에러가 뜨네요
```
[error] p.nettyException - Exception caught in Netty
java.lang.IllegalArgumentException: invalid version format: QﾍￓZ￝F{"￀+￀/ﾞￌￌￌ￀
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:102) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[io.netty.netty-3.9.3.Final.jar:na]
```

**Comment by npcode** [comment]
@KudoLayton 혹시 https로 쓰시는지요?

**Comment by KudoLayton** [comment]
네 그렇습니다.

**Comment by KudoLayton** [comment]
아, http로 하니 접속됩니다.

**Comment by npcode** [comment]
localhost에 https로 접근을 시도하면 저런 에러가 난다고 하네요.

http://stackoverflow.com/questions/21667254/play-framework-2-2-1-https-fails-on-connection-attempt
