### ISSUE TITLE
application.conf 를 읽어오지 못하는 문제

### ISSUE THREAD

**Issue by painh** [naver/yobi#927]
안녕하세요.

php-fpm이 떠 있는 서버에서 운영할 예정이라(php-fpm의 기본 포트가 9000입니다), port를 바꿀 생각 으로 application.conf를 수정했습니다만, 해당 설정이 로드 되지 않는듯 하여 질문합니다.

[root@server yobi]# bin/yobi -Dconfig.file=/var/www/yobi/conf/application.conf
/var/www/yobi/conf/application.conf
Play server process ID is 16615
[info] play - database [default] connected at jdbc:h2:file:./yobi
[error] n.s.e.Cache - Unable to set localhost. This prevents creation of a GUID. Cause was: server: server
java.net.UnknownHostException: server: server
        at java.net.InetAddress.getLocalHost(InetAddress.java:1473) ~[na:1.7.0_51]
        at net.sf.ehcache.Cache.<clinit>(Cache.java:214) ~[net.sf.ehcache.ehcache-core-2.6.8.jar:na]
        at net.sf.ehcache.config.ConfigurationHelper.createCache(ConfigurationHelper.java:296) [net.sf.ehcache.ehcache-core-2.6.8.jar:na]
        at net.sf.ehcache.config.ConfigurationHelper.createDefaultCache(ConfigurationHelper.java:219) [net.sf.ehcache.ehcache-core-2.6.8.jar:na]
        at net.sf.ehcache.CacheManager.configure(CacheManager.java:722) [net.sf.ehcache.ehcache-core-2.6.8.jar:na]
Caused by: java.net.UnknownHostException: server
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.7.0_51]
        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901) ~[na:1.7.0_51]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293) ~[na:1.7.0_51]
        at java.net.InetAddress.getLocalHost(InetAddress.java:1469) ~[na:1.7.0_51]
        at net.sf.ehcache.Cache.<clinit>(Cache.java:214) ~[net.sf.ehcache.ehcache-core-2.6.8.jar:na]
[info] play - Starting application default Akka system.
[info] play - Application started (Prod)
[info] application - User uploaded temporary files are cleaned up...(0 of 0)
Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:129)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:126)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer.<init>(NettyServer.scala:126)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:444)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(T

별개로, bin/yobi 안에 

###  ------------------------------- ###

declare -a YOBI_HOME='/var/www/yobi'

을 집어 넣어도 되질 않네요.

_JAVA_OPTIONS="-Dhttp.port=80" bin/yobi
으로 포트를 강제 지정하면 뜨긴 합니다만...

감사합니다.

**Comment by npcode** [comment]
application.conf의 port 정보는 yobi에게 포트 번호를 알려주기 위함이고(그래야 url 등을 올바르게 만들 수 있으므로), 사용하는 포트 번호를 변경하기 위한 것은 아닙니다. -Dhttp.port으로 포트 설정하시고 application.conf에서도 고쳐주시면 되겠습니다.

**Comment by painh** [comment]
넵 감사합니다!
