### ISSUE TITLE
yobi-0.8.1 마일스톤 글작성 에러 발생 문의

### ISSUE THREAD

**Issue by heoyongun** [naver/yobi#938]
yobi-0.8.1 사용

사용자 권한 - 관리자, svn 유저

1차 마일스톤 작성 정상 수행, 2일후 해당 유저(1차 마일스톤 계정)로 마일스톤 작성시

"서버 오류가 발생하여 서비스를 이용할 수 없습니다" 메세지 발생.

다른 프로젝트의 마일스톤 글작성시 동일한 현상 발생.

게시판 등은 정상 동작

**Comment by npcode** [comment]
서버에 에러로그가 남아있을 것 같은데 알려주시면 감사하겠습니다.

**Comment by heoyongun** [comment]
에러내역 입니다.


2015-06-30 15:53:09,517 - [INFO] - from access./files?containerType=MILESTONE&containerId=16 in play-akka.actor.default-dispatcher-770 
118.176.136.143 - 512gbyte [30/Jun/2015:15:53:09 +0900] "GET /files?containerType=MILESTONE&containerId=16 HTTP/1.1" 200 - "http://175.126.104.139:9000/512gbyte/chik-in/milestone/16/editform" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" 4ms

2015-06-30 15:53:11,891 - [ERROR] - from play in play-akka.actor.default-dispatcher-779 
Cannot invoke the action, eventually got an error: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update attachment set container_id=? where id=? and name=? and hash=? and container_type=? and mime_type=? and size=? and container_id=? and created_date=?] bind[null]

2015-06-30 15:53:11,894 - [ERROR] - from application in play-akka.actor.default-dispatcher-779 


! @6mj9io1e5 - Internal server error, for (POST) [/512gbyte/chik-in/milestone/16/edit] ->

play.api.Application$$anon$1: Execution exception[[OptimisticLockException: Data has changed. updated [0] rows sql[update attachment set container_id=? where id=? and name=? and hash=? and container_type=? and mime_type=? and size=? and container_id=? and created_date=?] bind[null]]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update attachment set container_id=? where id=? and name=? and hash=? and container_type=? and mime_type=? and size=? and container_id=? and created_date=?] bind[null]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:95) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:81) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:452) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:361) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.forceUpdate(DefaultPersister.java:172) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1651) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1640) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1617) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebean.Ebean.update(Ebean.java:496) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at play.db.ebean.Model.update(Model.java:137) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at models.Attachment.update(Attachment.java:345) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at models.Attachment.moveTo(Attachment.java:204) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at models.Attachment.moveAll(Attachment.java:166) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at controllers.MilestoneApp.editMilestone(MilestoneApp.java:172) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$115$$anonfun$apply$115.apply(routes_routing.scala:2462) ~[yobi.yobi-0.8.1.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$115$$anonfun$apply$115.apply(routes_routing.scala:2462) ~[yobi.yobi-0.8.1.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at Global$1.call(Global.java:190) ~[yobi.yobi-0.8.1.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:80) ~[yobi.yobi-0.8.1.jar:0.8.1]
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:21) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebean.Ebean.execute(Ebean.java:1264) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted

2015-06-30 15:53:11,896 - [INFO] - from access./512gbyte/chik-in/milestone/16/edit in play-akka.actor.default-dispatcher-779 
118.176.136.143 - - [30/Jun/2015:15:53:11 +0900] "POST /512gbyte/chik-in/milestone/16/edit HTTP/1.1" 500 - "http://175.126.104.139:9000/512gbyte/chik-in/milestone/16/editform" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" -

**Comment by npcode** [comment]
새 마일스톤 작성시가 아니라 수정할때만 에러가 발생하는 것인가요?

**Comment by npcode** [comment]
에러로그에는 첨부파일때문에 에러가 발생한 것으로 되어있는데, 실제로 파일을 첨부하셨는지요?

**Comment by heoyongun** [comment]
네 파일 첨부 했습니다.
그리고 새글 작성시에도 에러가 발생 합니다.

**Comment by heoyongun** [comment]
그리고 새글 쓸때 파일 첨부를 하지 않았는데.. 이전에 마일스톤  작성시 첨부한 파일이 따라다니는 현상도 확인했습니다.

**Comment by npcode** [comment]
@doortts 파일 따라다니는 문제 아직 남아있나요?

**Comment by heoyongun** [comment]
왜 그런지 모르겠지만... 지금은 해당건 재현 안되네요.

정상적으로 동작 됩니다. ;;

**Comment by npcode** [comment]
@heoyongun 24시간이 지나면 따라다니는 파일이 자동으로 삭제되기 때문에 그런 것일 수 있습니다. 그래도 따라다니면 안되는거니 문제인 것은 맞을 것 같네요.

**Comment by doortts** [comment]
첨부파일 관련해서는 최근에는 발생한 적이 1건 있었는데 그건 기존 작성시 업로드 하려다 그만 둔 파일이 코드리뷰시에 코멘트에 첨부파일이 따라 붙는 현상이 있었어요. 코드리뷰 에디터가 다른쪽의 에디터랑 조금 달라서 발생할 수 있어요.
