### ISSUE TITLE
윈도우에서 설치후 사용자 가입후 재시작했더니만 아래와 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by jjhangu** [naver/yobi#942]
Oops, cannot start the server.
javax.persistence.PersistenceException: The default EbeanServer has not been defined? This is normally set via the ebean.datasource.default property.
Otherwise it should be registered programatically via registerServer()
        at com.avaje.ebean.Ebean$ServerManager.getPrimaryServer(Ebean.java:178)
        at com.avaje.ebean.Ebean$ServerManager.access$300(Ebean.java:128)
        at com.avaje.ebean.Ebean.find(Ebean.java:1071)
        at Global.insertInitialData(Global.java:159)
        at Global.onStart(Global.java:138)
        at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by npcode** [comment]
#907 과 같은 문제인 것 같은데요. [README.md의 안내](https://github.com/naver/yobi#windows)에 따라 설정파일의 경로를 수동으로 직접 지정해보시면 어떨까요?

**Comment by snowshoehare** [comment]
@npcode 
초짜입니다 ^^;; 도움을 얻고자 코멘트 드립니다.
안내에 따라 명령어 수행 후 재실행하였더니 아래와 같이 경로 설정 오류가 발생하는데요.
제가 무엇을 잘못한 것 맞죠? 스샷 첨부 드립니다.


![yobi_](https://cloud.githubusercontent.com/assets/13324912/8664878/6c4e7574-2a18-11e5-957d-5195cd9c32f1.jpg)

**Comment by npcode** [comment]
@snowshoehare 지정한 위치에 설정 파일이 없어서 에러가 발생하고 있는데요. -Dconfig.file과 -Dlogger.file에는 실제로 존재하고 있는 설정 파일과 로그 설정 파일의 경로를 설정해주셔야 합니다. (그 위치에 새로 만드는 것이 아님)

처음에 그냥 bin\yobi.bat로 Yobi를 시작하시면 그 실행한 디렉토리에 conf/application.conf 등으로 설정파일이 생겨날텐데요. 원래대로라면 -Dconfig.file 등의 설정을 하지 않아도 그 파일을 찾아서 읽는 것이 정상입니다. 하지만 어떤 이유에서 그러지 못하는 경우 -Dconfig.file 등의 옵션을 주어서 수동으로 해당 파일을 지정하실 수 있습니다.

**Comment by snowshoehare** [comment]
@npcode 문제를 스스로 해결하여 자삭했는데 답변을 달아주셨네요. ^^ 감사합니다.
제가 윈도우로 셋업 중이었던지라 리눅스기반의 주소를 윈도우 형태로 변경하여 문제를 해결하였습니다. (리눅스쪽은 까막눈이라 ㅠ_ㅠ)
요비 폴더를 D파티션 최상위에 위치시켰으므로 아래와 같이 설정하여 문제를 해결하였습니다.

SET JAVA_OPTS=-Dyobi.home=d:\yobi-0.8.2 -Dconfig.file=d:\yobi-0.8.2\bin\conf\application.conf -Dlogger.file=d:\yobi-0.8.2\bin\conf\application-logger.xml

답변 감사드립니다.
