### ISSUE TITLE
윈도우 서버에서 안되서 linux에서 guide대로 설치했더니 에러가 뜨면서 안되네요..

### ISSUE THREAD

**Issue by jjhangu** [naver/yobi#944]
한번 사용해보고 싶은데 guide대로 했는데 잘 안되네요..

[weblogic@ettest yobi-0.8.2]$ ls
bin  lib  README.md  share
[weblogic@ettest yobi-0.8.2]$ cd bin/
[weblogic@ettest bin]$ ls
yobi  yobi.bat
[weblogic@ettest bin]$ ./yobi 
Play server process ID is 20853
Oops, cannot start the server.
@6mm301dp4: Cannot init the Global object
	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:59)
	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:53)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:52)
	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:402)
	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:402)
	at play.api.WithDefaultGlobal$class.global(Application.scala:68)
	at play.api.DefaultApplication.global(Application.scala:402)
	at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:82)
	at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:402)
	at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:402)
	at play.api.WithDefaultConfiguration$class.configuration(Application.scala:84)
	at play.api.DefaultApplication.configuration(Application.scala:402)
	at play.api.Application$class.$init$(Application.scala:274)
	at play.api.DefaultApplication.<init>(Application.scala:402)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.UnsupportedClassVersionError: Global : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:31)
	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:402)
	at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:402)
	at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:54)
	... 21 more
[weblogic@ettest bin]$

**Comment by doortts** [comment]
> Caused by: java.lang.UnsupportedClassVersionError: Global : Unsupported major.minor version 51.0

안녕하세요?
사용하고 계신 JAVA 버전을 알려주시겠어요?

**Comment by jjhangu** [comment]
1.6.0._31 버전으로 햇는데 1.7이상으로 다시 설치해볼게요..
