### ISSUE TITLE
도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by DaeJungHwang** [naver/yobi#945]
[ERROR] [07/14/2015 13:30:19.557] [Trireme Script Thread] [akka://sbt-web/user/$a/trireme-shell] Received a timeout probably because stdio sinks and sources were closed early given a timeout waiting for the JS to execute. Increase the timeout.
akka.pattern.AskTimeoutException: Recipient[Actor[akka://sbt-web/user/$a/stderr#1846813127]] had already been terminated.
        at akka.pattern.AskableActorRef$.ask$extension(AskSupport.scala:132)
        at akka.pattern.AskableActorRef$.$qmark$extension(AskSupport.scala:144)
        at akka.contrib.process.SinkStream.write(BlockingProcess.scala:290)
        at com.typesafe.jse.TriremeShell$$anonfun$receive$2$$anon$1.onComplete(Trireme.scala:125)
        at io.apigee.trireme.core.ScriptFuture.set(ScriptFuture.java:168)
        at io.apigee.trireme.core.ScriptFuture.run(ScriptFuture.java:184)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

이 에러때문에 start가 안됩니다. 
도와주세요 ㅠㅠ

**Comment by npcode** [comment]
설치하신 Play 버전이 2.3.6이 맞는지요?

**Comment by npcode** [comment]
2.3.7에서 저런 문제가 생긴다는 얘기가 있네요. https://groups.google.com/forum/#!topic/play-framework/TJdFx1eXQZA
