### ISSUE TITLE
sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found

### ISSUE THREAD

**Issue by ihoneymon** [naver/yobi#950]
아무런 생각없이 ```git pull origin master``` 를 하고서, 실행되지 않음에 흠칫...하여 찾아보니 많이 변했네요.
README와 이슈들을 살펴보면서 파일들 백업받고 **소스실행**을 하니 다음과 같이 의존성 라이브러리를 찾을 수 없다는 오류를 뱉고 맙니다.:
```
[info] Resolving org.apache.subversion#svn-javahl-api;1.8.1 ...
[error] Server access Error: Connection timed out url=http://maven.tmatesoft.com/content/repositories/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] 	module not found: org.apache.subversion#svn-javahl-api;1.8.1
[warn] ==== local: tried
[warn]   /home/ciman/.ivy2/local/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/home/ciman/activator-1.2.10-minimal/repository/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.apache.subversion/svn-javahl-api/1.8.1/ivys/ivy.xml
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== jgit-repository: tried
[warn]   http://download.eclipse.org/jgit/maven/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== scm-manager release repository: tried
[warn]   http://maven.scm-manager.org/nexus/content/groups/public/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== tmatesoft release repository: tried
[warn]   http://maven.tmatesoft.com/content/repositories/releases/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[warn] ==== julienrf.github.com: tried
[warn]   http://julienrf.github.com/repo/org/apache/subversion/svn-javahl-api/1.8.1/svn-javahl-api-1.8.1.pom
[info] Resolving com.google.code.findbugs#jsr305;3.0.0 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.subversion#svn-javahl-api;1.8.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] Wrote /home/ciman/activator-1.2.10-minimal/yobi/target/scala-2.10/yobi_2.10-0.8.2.pom
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found

Cannot start with errors.
```

그래서 ``` last *:update```으로 실행해보면, 
```
sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
	at sbt.IvySbt.withIvy(Ivy.scala:98)
	at sbt.IvySbt.withIvy(Ivy.scala:94)
	at sbt.IvySbt$Module.withModule(Ivy.scala:115)
	at sbt.IvyActions$.update(IvyActions.scala:125)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.subversion#svn-javahl-api;1.8.1: not found
```
를 출력.

조금 지난 후에 실행하면 될까요?

### Play activator
```
curl -O http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10-minimal.zip
```
을 이용해서 activator 를 다운로드 받아서 ```~/user/activator-1.2.10-minimal```로 압축해제하고
```
$ cd activator-1.2.10-minimal
$ git clone https://github.com/naver/yobi.git
$ cd yobi
$ ../activator
$ start -DapplyEvolutions.default=true -Dhttp.port=9000 -Dyobi.home=... -Dconfig.file
```
실행했습니다.

OS: 우분투 14.04 LTS 버전, 
JDK: 
```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```
입니다.

**Comment by npcode** [comment]
지금 tmatesoft의 maven 저장소가 죽은 것 아닌가 싶네요. 저도 아예 접근이 안되는군요. http://downforeveryoneorjustme.com/http://maven.tmatesoft.com 에서 보니까 죽었다고 나오네요.

패키지로 올라와있는 yobi를 받고 압축을 푸시면 그 안에는 svn 라이브러리가 들어있으니 그걸 사용하시는 방법도 있을 것 같습니다.

**Comment by ihoneymon** [comment]
tmatesoft의 메이븐 저장소가 복구가 된 듯 합니다. 현재는 빌드는 정상적으로 마쳤습니다.
