### ISSUE TITLE
포트를 80으로 변경시 오류가 납니다

### ISSUE THREAD

**Issue by ahb0327** [naver/yobi#969]
start -DapplyEvolutions.default=true -Dhttp.port=80 으로 리눅스에서
실행했는데 아래처럼 나오면서 꺼집니다

Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:80
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:129)
	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:126)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer.<init>(NettyServer.scala:126)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:275)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.net.SocketException: 허가 거부
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by seyriz** [comment]
다른 서버가 잡고있거나 특정한 운영체제에서는 80포트를 사용하려면 루트권한이 필요한 것도 있습니다.

**Comment by ahb0327** [comment]
@seyriz 감사합니다! 루트권한으로 했더니 되네요
