### ISSUE TITLE
application.log에 playException 에러가 났는데 크리티컬한 문제인가요?

### ISSUE THREAD

**Issue by Funalism** [naver/yobi#971]
안녕하세요. 
오랜만에 인사드립니다.
yobi를 운용중에 application.log에 아래와 같은 에러가 납니다.
크리티컬한 이슈인가요?

! @6n8op3dc2 - Internal server error, for (GET) [/] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1$$anonfun$apply$20.apply(PlayReloader.scala:236) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1$$anonfun$apply$20.apply(PlayReloader.scala:236) ~[na:na]
        at scala.Option.getOrElse(Option.scala:120) ~[scala-library.jar:na]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:236) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:230) ~[na:na]
        at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
        at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:230) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
        at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:90) ~[na:na]
        at scala.util.Either$LeftProjection.map(Either.scala:377) ~[scala-library.jar:na]
        at play.PlayReloader$$anon$1.reload(PlayReloader.scala:90) ~[na:na]
        at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:122) ~[play_2.10-2.3.6.jar:2.3.6]
        at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: sbt.compiler.CompileFailed: null
        at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
        at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
        at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
        at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
        at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:127) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:127) ~[na:na]
        at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:166) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:126) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:143) ~[na:na]
        at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:87) ~[na:na]
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:39) ~[na:na]
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:37) ~[na:na]
        at sbt.inc.IncrementalCommon.cycle(Incremental.scala:99) ~[na:na]
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38) ~[na:na]
        at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:37) ~[na:na]
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:65) ~[na:na]
        at sbt.inc.Incremental$.compile(Incremental.scala:37) ~[na:na]
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:27) ~[na:na]
        at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:157) ~[na:na]
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71) ~[na:na]
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:46) ~[na:na]
        at sbt.Compiler$.apply(Compiler.scala:75) ~[na:na]
        at sbt.Compiler$.apply(Compiler.scala:66) ~[na:na]
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:770) ~[na:na]
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762) ~[na:na]
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762) ~[na:na]
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47) ~[scala-library.jar:na]
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42) ~[na:na]
        at sbt.std.Transform$$anon$4.work(System.scala:64) ~[na:na]
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237) ~[na:na]
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18) ~[na:na]
        at sbt.Execute.work(Execute.scala:244) ~[na:na]
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237) ~[na:na]
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160) ~[na:na]
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30) ~[na:na]

**Comment by npcode** [comment]
컴파일 실패로 에러가 기록된 것 같은데요. 이런 경우 보통 다시 컴파일을 해서 문제가 해결되었을 것 같네요. Yobi를 소스코드를 받아 직접 빌드하여 사용하시는지요?

**Comment by Funalism** [comment]
@npcode 다시 컴파일을 해보겠습니다. yobi 소스코드를 받아서 activator로 실행합니다. 빌드를 다시 하진 않습니다. 만약 activator가 빌드를 해주는 것이라면 빌드 후 실행을 하는거겠네요.

**Comment by Funalism** [comment]
@npcode activator로 다시 실행을 하니 상기 에러가 나오지 않습니다.
activator가 빌드와 실행을 같이 해주는 매개체인가요?

**Comment by npcode** [comment]
네 맞습니다. activator가 그런 일을 합니다.

**Comment by Funalism** [comment]
@npcode 일단은 다시 컴파일 후에 올려보니 상기 에러가 또 나오진 않았습니다. 아무것도 나오지 않은것으로 보아 해결된 듯 하여 닫도록하겠습니다. 감사합니다.
