### ISSUE TITLE
알림 관련 문의드립니다.

### ISSUE THREAD

**Issue by Funalism** [naver/yobi#972]
안녕하세요.
알림 메일 관련 문의드립니다.
프로젝트를 git으로 만들고 yobi를 테스트 중입니다.
근데 git에 등록되어있는 그룹원들끼리 프로젝트 지켜보기를 활성화 시키고 알림을 모두 on으로 했습니다. 그럼 이후에 다른 그룹원이 이슈 및 코드를 올렸을 경우에 알림이 자동으로 메일을 통해서 전달될꺼라 생각했습니다. 그런데 다른기능은 제대로 동작하는데(git 소스업로드, 이슈에 코멘트남기기 등) 메일 알림만 제대로 동작을 안하네요. 그래서 issues에 검색을 통해 application.conf에 메일셋팅을 다음과 같이하였습니다.

smtp.user = "UserID"
smtp.password = "passwd"
smtp.mock = false 

그런데 이후에도 제대로 동작을 안하네요. 뭐가 문젤까요?
로그가 있으면 로그라도 보내드릴텐데
/logs/mail.log가 아예생성되지 않은 문제도 있네요.

Dconfig파일 옵션뒤에 Dlogger파일 옵션을 지정해주고 start를 했는데도 log파일이 application.log만 생성되어있네요. 

왜 저한테 이런 시련을 주시는지.. ㅠㅠ
이번주까지는 요비를 완전 마스터해야곘네요 ^^
답변기다리겠습니다.

**Comment by npcode** [comment]
mail.log에 기록이 없다면 메일 발송을 시도하기 전에 에러가 발생한 것으로 보입니다. 만약 메일 설정에 뭔가 문제가 있는게 원인이라면, smtp.mock=true로 설정하고 댓글을 달거나 하시면 메일 발송은 안되더라도 mail.log에 메일 발송 로그가 남을 것입니다. 확인 부탁드리겠습니다.

그리고 application-logger.xml의 mail 로그 레벨도 확인 부탁드립니다. 메일이 발송된 사실을 기록하는 로그 레벨은 INFO 라서요.

    <logger name="mail" level="INFO">
        <appender-ref ref="MAIL_LOG_FILE" />
    </logger>

**Comment by Funalism** [comment]
@npcode  smtp.mock=true로 설정하고 application-logger.xml mail 로그 레벨도 말씀하신 부분과 동일합니다.

관리자페이지에서 메일 발송을 해도 메일이 발송되지 않네요. 
제가 yobi start할때 상용하는 명령어는 다음과 같습니다.
start -Dyobi.home=/yobi/yobi -DapplyEvolutions.default=true -Dhttp.port=80 -Dconfig.file=/yobi/yobi/conf/application.conf -Dlogger.file=/yobi/yobi/conf/application-logger.xml

**Comment by npcode** [comment]
root.log나 application.log에 메일 발송과 관련된 에러가 기록되어 있지는 않은지요?

**Comment by Funalism** [comment]
@npcode 네 일단 root.log는 없고(위치가 어딘지 모르겠습니다. 한번 찾아볼께요) application.log에는 아무런 로그도 남아있지 않습니다. 혹시 로그 위치가 다른경로에 있을 수 있나요?

**Comment by npcode** [comment]
음 activator start로 실행할때도 -Dyobi.home 등이 잘 먹는지 모르겠네요. application-logger.xml을 별도 지정하셨으니 로그 파일 경로는 그에 따르겠지만, 그 경로도 아마 application.home의 상대경로로 되어있을 것 같군요. 혹시 target/universal/stage/logs에 생기지는 않았는지요?

**Comment by Funalism** [comment]
@npcode 네 말씀하신대로 stage/logs에 로그파일이 있네요. 
궁금한것이 stage/conf 에 application.conf 파일을 제가 .old파일로 복사 후 삭제하고, 
다시 activator로 yobi를 실행하였는데 application.conf 파일이 stage/conf 경로에 생성되지 않네요? 
말씀하신대로 smtp.mock=ture 옵션이 적용된 application.conf 파일은 $설치경로/yobi/target/scala-2.10/classes 여기에 적용되네요. 경로설정이 문제인듯한데, 복잡하네요. 
저번에 말씀드렸던 application.sizeName도 적용이 안되는 이유도 경로문제였나보네요.
https://github.com/naver/yobi/issues/967

--------------------- Mail 로그를 확인해보니. 
2015-09-16 09:15:53,407 - [INFO] - from mail.out in application-akka.actor.default-dispatcher-4
"Re: [Yobi_Test] 메일 테스트 합니다. (#10)" [=?UTF-8?B?6rOg67OR7IiY?= <a@a.com>, Yobi <yobiproject.mail@gmail.com>, =?UTF-8?B?6rmA7J2Y7KSR?= <b@b.com>, =?UTF-8?B?7Iug7IiY7ZmN?= <c@c.com>]

이런 로그가 있네요. 개인정보로 인해 실제메일주소는 a,b,c로 변경하였습니다. 
로그를 볼땐 제대로 수행하고 있는건가요? 실제 메일은 오지 않습니다.

**Comment by Funalism** [comment]
@npcode /yobi/conf/에 있는 application.conf, application-logger.xml 파일을 강제로 불러오게 할 순 없나요? 그게 start -Dconfig & -Dlogger 명령어인듯한데 ,, 혹시 제가 두개파일을 stage/conf 에 강제로 넣어도 적용이 될까요?

**Comment by npcode** [comment]
1. 설정 파일 디렉토리 관련

제가 보기엔 그냥 로그 파일만 target/universal/stage/logs에 생기고 나머지는 지정하신대로 동작할 것 같은데요. 로그 파일만 저렇게 동작하는 이유는, 로그 설정 파일이 application.home의 상대경로로 설정되어있는데 application.home이 yobi.home이 아니라 user.dir이고 user.dir은 app_home이며 app_home은 target/universal/stage이기 때문입니다. (Play가 activator를 도입하기 시작하면서 이렇게 복잡해졌습니다...)
-Dyobi.home이 아니라 YOBI_HOME 환경변수를 이용하면(`YOBI_HOME=/yobi/yobi activator`로 activator 실행) user.dir을 YOBI_HOME으로 설정할 수 있지 않을까 싶네요.

2. 메일 발송 관련

만약 mail.log에서 메일이 발송된 것으로 되어있는데도 메일이 보내지지 않고 있다면 Yobi가 시스템의 MTA를 통해 메일 발송을 요청하는데는 성공했지만 어떤 이유에서인지 발송이 안된 것일 수 있습니다. 따라서 시스템의 메일 로그(예: /var/log/maillog)를 확인해 볼 필요가 있습니다. 아마 메일 발송이 실패한 이유가 기록되어 있을 것입니다.

**Comment by Funalism** [comment]
@npcode 감사합니다. 확인하고 코멘트 달겠습니다. ^^

**Comment by Funalism** [comment]
@npcode 다른문제가 생겼네요. 이제 java 가 올라오지 않네요. 
../activator 후에  start -DapplyEvolutions.default=true -Dhttp.port=80 -Dconfig.file=/home/dev/activator-1.2.10-minimal/yobi/conf/application.conf 명령어로 실행하면 프로세스 id 나오면서 실행이 되었다 나오는데. ps -ef | grep java로 검색하보면 java가 올라와있는게 없네요. 어떤 문제일까요?

**Comment by npcode** [comment]
@Funalism 실행했을 때 아무런 에러도 없나요?

**Comment by Funalism** [comment]
@npcode 네 그렇습니다. 일단 stage폴더를 백업하고 clean하고 다시 빌드하고 있는 중입니다.
확인 후 코멘트하겠습니다. 감사합니다.

**Comment by Funalism** [comment]
@npcode 일단 앱이 백그라운드에 실행되어 있어서 제대로 실행이 되지 않네요. 
RUNNING PID 폴더의 pid 값으로 앱을 죽이고 RUNNING_PID파일도 삭제해줘야 앱이 구동되네요? 신기하네요 ㅎㅎ  이건별개로 아예 첨부터 싹 밀고 다시 셋팅했습니다.
알림 메일 테스트 전에 일단 관리자 아이디로 테스트 계정에 메일을 보내봤습니다.
그랬더니 서버 오류가 발생하여 서비스를 이용할 수 없습니다라는 메세지와 로그는 아래처럼 나오네요.

[error] play - Cannot invoke the action, eventually got an error: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
[error] application -

! @6nfb8951i - Internal server error, for (POST) [/sites/mail] ->

play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : smtp.gmail.com:465]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1401) ~[org.apache.commons.commons-email-1.3.1.jar:1.3.1]
        at org.apache.commons.mail.Email.send(Email.java:1428) ~[org.apache.commons.commons-email-1.3.1.jar:1.3.1]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 cn4sm1067160pbc.94 - gsmtp

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
[info] a./sites/mail - 10.1.98.1 - - [17/Sep/2015:12:57:50 +0900] "POST /sites/mail HTTP/1.1" 500 - "http://@@@@@@/sites/mail" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36" -
[info] a./messages.js - 10.1.98.1 - admin [17/Sep/2015:12:57:50 +0900] "GET /messages.js HTTP/1.1" 200 - "http://@@@@@@@/sites/mail" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36" 12ms
[warn] application - Failed to send a notification: models.NotificationMail$EventEmail@18f8d23
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1401)
        at org.apache.commons.mail.Email.send(Email.java:1428)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54)
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68)
        at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8)
        at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15)
        at models.NotificationMail.sendMail(NotificationMail.java:513)
        at models.NotificationMail.sendNotification(NotificationMail.java:426)
        at models.NotificationMail.access$100(NotificationMail.java:68)
        at models.NotificationMail$1.sendMail(NotificationMail.java:160)
        at models.NotificationMail$1.run(NotificationMail.java:123)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 yt9sm1097682pac.32 - gsmtp

        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1391)
        ... 18 more


@@@@@@@@@@@@라고 표시한 부분은 내부 도메인입니다.

**Comment by Funalism** [comment]
@npcode application.conf 내 메일 셋팅은 다음과 같습니다.

smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true

smtp.user = "제 gmail 계정"
smtp.password = "gmail 계정 패스워드"
smtp.domail = gmail.com
smtp.mock = true

smtp.mock는 true로 해보고 false로도 해봤는데 마찬가지네요.

**Comment by Funalism** [comment]
@npcode #761과 같은 이슈같습니다. 일단 비밀번호에 특수문제를 제외하고 테스트를 해보고 비밀번호를 다시 한번 확인해보겠습니다.

**Comment by Funalism** [comment]
@npcode 해결했습니다.
설정상의 문제라기보단 구글 정책 문제였네요. 
![success](https://cloud.githubusercontent.com/assets/13342100/9925600/442f3eee-5d48-11e5-9722-757ffb6d0e10.jpg)

혹 저와 같은 문제를 겪으신분들은 구글의 내 계정 -> 계정설정에 들어가셔서 로그인 및 보안탭에 보안수준이 낮은 앱 허용: 사용으로 꼭 바꿔주셔야 합니다.
