### ISSUE TITLE
out of memory 로그 첨부

### ISSUE THREAD

**Issue by jjhangu** [naver/yobi#981]
안녕하세요 
지금 프로젝트를 yobi를 통해서 사용하는데요 yobi 실 사용자는 30명쯤 되고 있습니다.

사용버전은 아래와 같고
yobi-0.8.2

요비 start 옵션은 아래와 같습니다.
JAVA_OPTIONS="-Xmx1024m -Xms2048m" nohup ./yobi > admin.out 2>&1 &

2일에 한번씩 아래와 같이 아웃오브 메모리가 나서 요비를 재시작해줘야하는 어려움이 있는데요..
yobi가 메모리를 많이 차지 하나요??? 

해당 서버에 8giga 에 오라클과 같이 사용하고 있어서 빠듯하긴 한데 
java_options 쪽에 메모리를 더 높혀줘야 할까요??

2015-10-07 13:21:09,604 - [ERROR] - from akka.actor.ActorSystemImpl in play-akka.actor.default-dispatcher-260 
Uncaught error from thread [play-akka.actor.default-dispatcher-243] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
	at utils.PlayServletResponse$ChunkedOutputStream.<init>(PlayServletResponse.java:62) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at utils.PlayServletResponse.<init>(PlayServletResponse.java:119) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at controllers.SvnApp.startDavService(SvnApp.java:145) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at controllers.SvnApp.service(SvnApp.java:129) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at controllers.SvnApp.serviceWithPath(SvnApp.java:70) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$168$$anonfun$apply$168.apply(routes_routing.scala:2886) ~[yobi.yobi-0.8.2.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$168$$anonfun$apply$168.apply(routes_routing.scala:2886) ~[yobi.yobi-0.8.2.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at Global$1.call(Global.java:190) ~[yobi.yobi-0.8.2.jar:na]
	at utils.BasicAuthAction.call(BasicAuthAction.java:115) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]

**Comment by doortts** [comment]
안녕하세요?
우선 적어주신 내용으로봐서는 Xmx1024m -Xms2048m 가 반대로 되어 있는걸로 보입니다. 
Xmx 쪽이 max 입니다. 그리고 메모리 1g는 부족하고 (몇 가지 이유로) 최소 3기가 이상 잡아주시면 좋을 것 같습니다.

**Comment by jjhangu** [comment]
제일 처음에는 Xmx2048m -Xms2048m 로 셋팅을 했었는데 한번씩 메모리 부족현상이 있어서 재시작을 해서 최소값을 1024로 한다는것을 제가 잘못적용을 했네요.. 일단 max값을 더 올려서 운영을 해볼게요.. 답변 감사합니다.
