### ISSUE TITLE
activator 실행시 오류 입니다. 

### ISSUE THREAD

**Issue by AhnTaeHee** [naver/yobi#983]
## Windows의 경우
activator 이후에 yobi 프롬프트에서 start 명령 이후에 
> 입력 줄이 너무 깁니다. 명령 구문이 올바르지 않습니다.

라는 메시지가 출력됩니다.(아래 이미지 참조) 

![cap 2015-10-12 13-17-29-170](https://cloud.githubusercontent.com/assets/3633905/10421448/9b6d1d94-70e3-11e5-843b-469ea93c0548.png)
 

## Linux의 경우 
activator 명령 실행시에 
```
/home/yobi/activator-1.2.10-minimal/yobi/build.sbt:2: error: object file is not a member of package java.nio
```
위와 같은 에러와 함께 
```
sbt.compiler.EvalException: Type error in expression
        at sbt.compiler.Eval.checkError(Eval.scala:343)
        at sbt.compiler.Eval.compileAndLoad(Eval.scala:165)
        at sbt.compiler.Eval.evalCommon(Eval.scala:135)
        at sbt.compiler.Eval.evalDefinitions(Eval.scala:109)
        at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:197)
        at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:99)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:507)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:502)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:501)
        at scala.Option.getOrElse(Option.scala:120)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:501)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
        at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:500)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadSettings$1(Load.scala:500)
        at sbt.Load$.sbt$Load$$expand$1(Load.scala:523)
        at sbt.Load$.loadSettings(Load.scala:528)
        at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
        at sbt.Load$.defaultLoad$1(Load.scala:475)
        at sbt.Load$.loadTransitive(Load.scala:478)
        at sbt.Load$.loadProjects$1(Load.scala:418)
        at sbt.Load$.loadUnit(Load.scala:419)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
        at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
        at sbt.BuildLoader.apply(BuildLoader.scala:143)
        at sbt.Load$.loadAll(Load.scala:312)
        at sbt.Load$.loadURI(Load.scala:264)
        at sbt.Load$.load(Load.scala:260)
        at sbt.Load$.load(Load.scala:251)
        at sbt.Load$.apply(Load.scala:134)
        at sbt.Load$.defaultLoad(Load.scala:37)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$.process(Command.scala:95)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.State$$anon$1.process(State.scala:179)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:100)
        at sbt.MainLoop$.run(MainLoop.scala:93)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
        at sbt.MainLoop$.runLogged(MainLoop.scala:25)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:19)
        at xsbt.boot.Boot$.runImpl(Boot.scala:44)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
```

이런 에러로그가 발생합니다. (아래 사진 참조) 

![cap 2015-10-12 13-21-40-483](https://cloud.githubusercontent.com/assets/3633905/10421486/30da403c-70e4-11e5-8476-7466a4bc38fa.png)

어떻게 실행할 수 있을까요? 
설치를 시도한 환경정보는 아래와 같습니다. 
> Window: Windows10 64bit, JDK 1.7
> Linux: Centos 5.5, JDK 1.7 

갑사합니다.

**Comment by npcode** [comment]
> 입력 줄이 너무 깁니다

이건 sbt의 버그로 알려져있는데 yobi를 설치하는 경로명을 짧게 줄이는 것 외엔 딱히 방법이 없어보입니다. 아니면 소스코드가 아니라 패키지로 설치하거나요.

> /home/yobi/activator-1.2.10-minimal/yobi/build.sbt:2: error: object file is not a member of package java.nio

이건 자바 버전 때문이 아닐까 싶은데, java와 javac 모두 1.7 이상이 맞는지요?

**Comment by UnRyongPark** [comment]
![jdk1780](https://cloud.githubusercontent.com/assets/6115168/10596185/5dcec49e-771c-11e5-8b22-0a34b1349631.PNG)
![jdk1860](https://cloud.githubusercontent.com/assets/6115168/10596186/5dd21f86-771c-11e5-8215-f3648647b4a1.PNG)


저도 동일한 문제가 발생하고 있습니다.

Windows 2012 R2 64bit JDK 1.7.80
Windows 2012 R2 64bit JDK 1.8.60

경로: F:\yobi\yobi


※ 홈페이지에서 다운받아서 실행하는 zip파일은 어째선지 conf파일 변경 적용이 안되서 소스파일 받아서 적용해봤는데 이건 아예 실행이 안되네요;ㅅ;

**Comment by syakuis** [comment]
1. yobi github 릴리즈에서 패키지 내려받고 c:\yobi 에 셋팅하고 한번 실행 후 종료 (소스는 안됩니다.)
2. 기존 설정파일 및 백업 파일 복사하기
3. 구동옵션 필요함.
```
SET JAVA_OPTS=-Dyobi.home=%yobi% -Dconfig.file=%yobi%\conf\application.conf -Dlogger.file=%yobi%\conf\application-logger.xml -Dhttp.port=9000
```
실행

**c:/.../yobi 같은 경로도 똑같은 오류가 발생합니다.**

### 한글문제
application.conf 수정
```
application.langs="en-US, ko-KR, ja-JP"
```
