### ISSUE TITLE
0.7.3버전에서 업그레이드 후 문제 문의드립니다

### ISSUE THREAD

**Issue by l2zeo** [naver/yobi#999]
zip 으로 압축해제후 conf / repo / db 를  0.7.3 버전에서 옮기고 
../play start 를 해보니 아래와 같이 출력되더라구요. 무엇을 더 해줘야 하는지요??

java.lang.NoClassDefFoundError: scala/StringContext
	at sbt.CommandStrings$.<init>(CommandStrings.scala:85)
	at sbt.CommandStrings$.<clinit>(CommandStrings.scala)
	at sbt.BuiltinCommands$.defaults(Main.scala:209)
	at sbt.xMain.run(Main.scala:30)
	at xsbt.boot.Launch$.run(Launch.scala:55)
	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	at xsbt.boot.Launch$.launch(Launch.scala:69)
	at xsbt.boot.Launch$.apply(Launch.scala:16)
	at xsbt.boot.Boot$.runImpl(Boot.scala:31)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scala.StringContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 11 more
Error during sbt execution: java.lang.NoClassDefFoundError: scala/StringContext

**Comment by hoyajigi** [comment]
아마도 play 버전이 안 맞아서 그런거 같은데요?
Play 2.3을 다운 받으시고 Activator를 이용해 보세요~

**Comment by l2zeo** [comment]
@hoyajigi 안녕하세요. Play 2.3 을 어디서 다운해야 하는건가요??
Activator로 진행하면 잘되긴합니다만...

**Comment by l2zeo** [comment]
한가지더.. 0.7.3 버전에서는 yobi 폴더에서 ../play 하면 실행이 되었는데요.
지금은 ../activator 로 해야 실행이 되던데요 이상태에서 빠져나올려면 어떻게 해야 하나요?
백그라운드로 돌게끔두고요. 

실행을 중지하려면 kill 뿐이 없는지도 궁금합니다.
